In [1]:
import os
import json
import requests
import pandas as pd
import requests
import warnings
from bs4 import BeautifulSoup

warnings.filterwarnings("ignore")
os.makedirs("./BaseInfo",exist_ok=True)

# 產業別

In [2]:
#解碼產業別使用
aa='{"\\u4e0a\\u5e02\\u516c\\u53f8\\u7522\\u696d\\u985e\\u5225":{"1":"\\u6c34\\u6ce5\\u5de5\\u696d","2":"\\u98df\\u54c1\\u5de5\\u696d","3":"\\u5851\\u81a0\\u5de5\\u696d","4":"\\u7d21\\u7e54\\u7e96\\u7dad","5":"\\u96fb\\u6a5f\\u6a5f\\u68b0","6":"\\u96fb\\u5668\\u96fb\\u7e9c","7":"\\u5316\\u5b78\\u5de5\\u696d","8":"\\u751f\\u6280\\u91ab\\u7642\\u696d","9":"\\u73bb\\u7483\\u9676\\u74f7","10":"\\u9020\\u7d19\\u5de5\\u696d","11":"\\u92fc\\u9435\\u5de5\\u696d","12":"\\u6a61\\u81a0\\u5de5\\u696d","13":"\\u6c7d\\u8eca\\u5de5\\u696d","14":"\\u534a\\u5c0e\\u9ad4\\u696d","15":"\\u96fb\\u8166\\u53ca\\u9031\\u908a\\u8a2d\\u5099\\u696d","16":"\\u5149\\u96fb\\u696d","17":"\\u901a\\u4fe1\\u7db2\\u8def\\u696d","18":"\\u96fb\\u5b50\\u96f6\\u7d44\\u4ef6\\u696d","19":"\\u96fb\\u5b50\\u901a\\u8def\\u696d","20":"\\u8cc7\\u8a0a\\u670d\\u52d9\\u696d","21":"\\u5176\\u4ed6\\u96fb\\u5b50\\u696d","22":"\\u5efa\\u6750\\u71df\\u9020","23":"\\u822a\\u904b\\u696d","24":"\\u89c0\\u5149\\u4e8b\\u696d","25":"\\u91d1\\u878d\\u4fdd\\u96aa","26":"\\u8cbf\\u6613\\u767e\\u8ca8","27":"\\u6cb9\\u96fb\\u71c3\\u6c23\\u696d","28":"\\u7d9c\\u5408","29":"\\u5176\\u4ed6","30":"--","31":"--","32":"--","33":"--"},"\\u4e0a\\u6ac3\\u516c\\u53f8\\u7522\\u696d\\u985e\\u5225":{"1":"--","2":"\\u98df\\u54c1\\u5de5\\u696d","3":"\\u5851\\u81a0\\u5de5\\u696d","4":"\\u7d21\\u7e54\\u7e96\\u7dad","5":"\\u96fb\\u6a5f\\u6a5f\\u68b0","6":"\\u96fb\\u5668\\u96fb\\u7e9c","7":"\\u5316\\u5b78\\u5de5\\u696d","8":"\\u751f\\u6280\\u91ab\\u7642\\u696d","9":"\\u73bb\\u7483\\u9676\\u74f7","10":"--","11":"\\u92fc\\u9435\\u5de5\\u696d","12":"\\u6a61\\u81a0\\u5de5\\u696d","13":"--","14":"\\u534a\\u5c0e\\u9ad4\\u696d","15":"\\u96fb\\u8166\\u53ca\\u9031\\u908a\\u8a2d\\u5099\\u696d","16":"\\u5149\\u96fb\\u696d","17":"\\u901a\\u4fe1\\u7db2\\u8def\\u696d","18":"\\u96fb\\u5b50\\u96f6\\u7d44\\u4ef6\\u696d","19":"\\u96fb\\u5b50\\u901a\\u8def\\u696d","20":"\\u8cc7\\u8a0a\\u670d\\u52d9\\u696d","21":"\\u5176\\u4ed6\\u96fb\\u5b50\\u696d","22":"\\u5efa\\u6750\\u71df\\u9020","23":"\\u822a\\u904b\\u696d","24":"\\u89c0\\u5149\\u4e8b\\u696d","25":"\\u91d1\\u878d\\u696d","26":"\\u8cbf\\u6613\\u767e\\u8ca8","27":"\\u6cb9\\u96fb\\u71c3\\u6c23\\u696d","28":"--","29":"\\u5176\\u4ed6","30":"\\u6587\\u5316\\u5275\\u610f\\u696d","31":"\\u8fb2\\u696d\\u79d1\\u6280\\u696d","32":"\\u96fb\\u5b50\\u5546\\u52d9","33":"\\u7ba1\\u7406\\u80a1\\u7968"},"\\u65b0\\u7de8\\u78bc":{"1":"01","2":"02","3":"03","4":"04","5":"05","6":"06","7":"21","8":"22","9":"08","10":"09","11":"10","12":"11","13":"12","14":"24","15":"25","16":"26","17":"27","18":"28","19":"29","20":"30","21":"31","22":"14","23":"15","24":"16","25":"17","26":"18","27":"23","28":"19","29":"20","30":"32","31":"33","32":"34","33":"80"}}'
dd= json.loads(aa)
mappingData=pd.DataFrame.from_dict(dd).dropna()
mappingData=mappingData.dropna()
mappingData['新編碼']=mappingData['新編碼'].apply(lambda x:str(x).zfill(2))
mappingData.loc[len(mappingData.index)] = ['電子工業', '電子工業', '13'] 
mappingData.loc[len(mappingData.index)] = ['綠能環保', '綠能環保', '35'] 
mappingData.loc[len(mappingData.index)] = ['數位雲端', '數位雲端', '36'] 
mappingData.loc[len(mappingData.index)] = ['運動休閒', '運動休閒', '37'] 
mappingData.loc[len(mappingData.index)] = ['居家生活', '居家生活', '38'] 

mappingData.sort_values(by=['新編碼'])

    上市公司產業類別  上櫃公司產業類別 新編碼
1       水泥工業        --  01
2       食品工業      食品工業  02
3       塑膠工業      塑膠工業  03
4       紡織纖維      紡織纖維  04
5       電機機械      電機機械  05
6       電器電纜      電器電纜  06
9       玻璃陶瓷      玻璃陶瓷  08
10      造紙工業        --  09
11      鋼鐵工業      鋼鐵工業  10
12      橡膠工業      橡膠工業  11
13      汽車工業        --  12
33      電子工業      電子工業  13
22      建材營造      建材營造  14
23       航運業       航運業  15
24      觀光事業      觀光事業  16
25      金融保險       金融業  17
26      貿易百貨      貿易百貨  18
28        綜合        --  19
29        其他        其他  20
7       化學工業      化學工業  21
8      生技醫療業     生技醫療業  22
27     油電燃氣業     油電燃氣業  23
14      半導體業      半導體業  24
15  電腦及週邊設備業  電腦及週邊設備業  25
16       光電業       光電業  26
17     通信網路業     通信網路業  27
18    電子零組件業    電子零組件業  28
19     電子通路業     電子通路業  29
20     資訊服務業     資訊服務業  30
21     其他電子業     其他電子業  31
30        --     文化創意業  32
31        --     農業科技業  33
32        --      電子商務  34
34      綠能環保      綠能環保  35
35      數位雲端      數位雲端  36
36      運動休閒      運動休閒  37
37      居家生活      居家生活  38
33        --      管理股票  80

    上市公司產業類別  上櫃公司產業類別 新編碼
1       水泥工業        --  01
2       食品工業      食品工業  02
3       塑膠工業      塑膠工業  03
4       紡織纖維      紡織纖維  04
5       電機機械      電機機械  05
6       電器電纜      電器電纜  06
9       玻璃陶瓷      玻璃陶瓷  08
10      造紙工業        --  09
11      鋼鐵工業      鋼鐵工業  10
12      橡膠工業      橡膠工業  11
13      汽車工業        --  12
33      電子工業      電子工業  13
22      建材營造      建材營造  14
23       航運業       航運業  15
24      觀光事業      觀光事業  16
25      金融保險       金融業  17
26      貿易百貨      貿易百貨  18
28        綜合        --  19
29        其他        其他  20
7       化學工業      化學工業  21
8      生技醫療業     生技醫療業  22
27     油電燃氣業     油電燃氣業  23
14      半導體業      半導體業  24
15  電腦及週邊設備業  電腦及週邊設備業  25
16       光電業       光電業  26
17     通信網路業     通信網路業  27
18    電子零組件業    電子零組件業  28
19     電子通路業     電子通路業  29
20     資訊服務業     資訊服務業  30
21     其他電子業     其他電子業  31
30        --     文化創意業  32
31        --     農業科技業  33
32        --      電子商務  34
34      綠能環保      綠能環保  35
35      數位雲端      數位雲端  36
36      運動休閒      運動休閒  37
37      居家生活      居家生活  38
33        --      管理股票  80

# 上市公司基本資料

In [3]:
#【上市公司基本資料】
#https://data.gov.tw/dataset/18419 
url='https://mopsfin.twse.com.tw/opendata/t187ap03_L.csv'
headers = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"
}
req = requests.get(url, headers = headers,verify=False)
data = req.content.decode('utf8')
df_listing = pd.DataFrame([x.replace('"','').split(',') for x in data.split('\n')])
df_listing  = pd.DataFrame(df_listing .values[1:], columns=df_listing .iloc[0])
df_listing['Type']='上市'
df_listing1=df_listing[['公司代號', '公司名稱', '公司簡稱','產業別','實收資本額','Type']]
#【解碼產業】
#【Data 合併】
df_listing2=pd.merge(df_listing1, mappingData, how='left', left_on='產業別', right_on='新編碼')

In [4]:
data

'\ufeff出表日期,公司代號,公司名稱,公司簡稱,外國企業註冊地國,產業別,住址,營利事業統一編號,董事長,總經理,發言人,發言人職稱,代理發言人,總機電話,成立日期,上市日期,普通股每股面額,實收資本額,私募股數,特別股,編制財務報表類型,股票過戶機構,過戶電話,過戶地址,簽證會計師事務所,簽證會計師1,簽證會計師2,英文簡稱,英文通訊地址,傳真機號碼,電子郵件信箱,網址,已發行普通股數或TDR原股發行股數\r\n"1150205","1101","臺灣水泥股份有限公司","台泥","－ ","01","台北市中山北路2段113號","11913502","張安平","程耀輝","葉毓君","永續長","賴家柔","(02)2531-7099","19501229","19620209","新台幣                 10.0000元","77511817420","0","200000000","1","中國信託商業銀行代理部","66365566","台北市重慶南路一段83號5樓","勤業眾信聯合會計師事務所","翁雅玲","黃惠敏","TCC","No.113, Sec.2, Zhongshan N. Rd.,Taipei City 104,Taiwan (R.O.C.)","(02)2531-6529","finance@taiwancement.com","https://www.tccgroupholdings.com/tw/","7551181742"\r\n"1150205","1102","亞洲水泥股份有限公司","亞泥","－ ","01","台北市大安區敦化南路2段207號30、31樓","03244509","徐旭東","李坤炎","王照宇","協理","楊淯玲","02-2733-8000","19570321","19620608","新台幣                 10.0000元","35465628810","0","0","1","亞東證券股份有限公司","02-7753-1699","新北市板橋區新站路16號13樓","勤業眾信聯合會計師事務所","戴信維","池瑞全","ACC","30-31F., No.207, Sec. 2, Dunhua S. Rd., Da\' an Dist., Taipei City 106, TaiwanTAIPEI,TAIWAN,R.O.C","02-2736-6263","service@acc.com.tw","www.acc.com.tw","3546562881"\r\n"1150205","1103","嘉新水泥股份有限公司","嘉泥","－ ","01","台北市中山北路二段96號","11892801","張剛綸","王立心","金哲毅","董事會秘書室資深經理","馮文裕","(02)2551-5211","19541213","19691114","新台幣                 10.0000元","7902474590","0","0","1","群益金鼎證券股份有限公司股代部","(02)2702-3999","台北市敦化南路2段97號地下2樓","勤業眾信聯合會計師事務所","陳薔旬","梁盛泰","CHC","No.96, Sec. 2, Zhongshan N. Rd., Zhongshan Dist.Taipei City 10449, Taiwan (R.O.C.)","(02)2511-4002","ir@chcgroup.com.tw","www.chcgroup.com.tw","790247459"\r\n"1150205","1104","環球水泥股份有限公司","環泥","－ ","01","台北市南京東路二段125號10樓","07568009","博智投資股份有限公司","侯智升","楊宗仁","副總經理","高琮堯","02-25077801","19600321","19710201","新台幣                 10.0000元","6866818160","0","0","1","永豐金證券股份有限公司","02-23816288","台北市博愛路17號3樓","勤業眾信聯合會計師事務所","李季珍","廖鴻儒","UCC","10th F., 125 Nanking E.Rd Sec. 2,Taipei Taiwan","02-25075870","ucc@ucctw.com","www.ucctw.com","686681816"\r\n"1150205","1108","幸福水泥股份有限公司","幸福","－ ","01","台北市松江路237號15樓","40601248","陳韻如","陳明賢","溫秀菊","財務部經理","陳一誠","25092188","19740507","19900606","新台幣                 10.0000元","4047380490","0","0","1","永豐金證券股務代理","2381-6288","台北市中正區博愛路17號3樓","勤業眾信聯合會計師事務所","陳招美","陳薔旬","LUCKY CEMENT","15TH FL.,NO.237,SUNG KIANG RD.,TAIPEI,TAIWAN,R.O.C.","25048672","wendy@luckygrp.com.tw","www.luckygrp.com.tw","404738049"\r\n"1150205","1109","信大水泥股份有限公司","信大","－ ","01","台北市寶慶路37號7樓","03279507","楊智雄","楊大寬","張清壽","資深協理","蔡素秋","(02)23816731","19640315","19911205","新台幣                 10.0000元","3411588680","0","0","1","中國信託商業銀行代理部","(02)6636-5566","台北巿重慶南路一段83號5樓","資誠聯合會計師事務所","李秀玲","支秉鈞","HsingTa","No. 37, 7F, Baoqing Rd.,Taipei City 100, Taiwan (R.O.C.)","23314086","service@hsingta.com.tw","www.hsingta.com.tw","341158868"\r\n"1150205","1110","東南水泥股份有限公司","東泥","－ ","01","高雄市前金區五福三路21號4樓之1","83078600","陳敏斷","吳炎輝","黃薪翰","財務部副總經理","唐榮宗","07-2711121","19561228","19941022","新台幣                 10.0000元","5720007970","0","0","1","元大證券股份有限公司","02-25865859","臺北市大安區敦化南路2段67號地下一樓","國富浩華聯合會計師事務所","黃致富","黃鈴雯","SE CEMENT","NO.21 Wu Fu 3 RoadKaohsiung, Taiwan, R.O.C.","07-9505895","southeast@secement.com","www.southeastcement.com.tw","572000797"\r\n"1150205","1201","味全食品工業股份有限公司","味全","－ ","02","台北市松江路125號","11347802","徐文芳","滕以勇","李文學","財務長","待補","(02)25065020","19530922","19620209","新台幣                 10.0000元","5060629140","0","0","1","元大證券股務代理部","(02)25865859","臺北市大安區敦化南路2段67號地下一樓","資誠聯合會計師事務所","黃世鈞","葉翠苗","WEI CHUAN","10F., No.125, Sung Chiang Rd.Taipei, Taiwan, R.O.C.","(02)25063182","service@weichuan.com.tw","https://www.weichuan.com.tw","506062914"\r\n"1150205","1203","味王股份有限公司","味王","－ ","02","台北市中山北路二段79號5樓","07067309","陳清福","陳恭平","魏璟雄","協理","李兆弘","(02)25717271","19590704","19640824","新台幣                 10.0000元","2400000000","0","0","1","群益金鼎證券股份有限公司","27023999","台北市敦化南路二段97號地下2樓","大中國際聯合會計師事務所","溫明郁","張卉諭","VE WONG","5TH FL., 79 CHUNG SHAN N. RD., SEC.2TAIPEI TAIWAN","(02)25811006","wei@vewong.com.tw","https://www.vewong.com/","240000000"\r\n"1150205","1210","大成長城企業股份有限公司","大成","－ ","02","台南市永康區蔦松二街三號","73008303","韓家宇","韓芳豪","夏銜譽","副總經理","許博涵","06-2531111","19601228","19780520","新台幣                 10.0000元","8947672220","0","0","1","中國信託商業銀行代理部","02-66365566","台北市重慶南路一段八十三號六樓","安侯建業會計師事務所","李逢暉","蔡佩汝","GREATWALL","3 NIAOSUN 2TH STREETYONGKONG TAINAN CONTY TAIWAN","06-2534596","ir@ms.greatwall.com.tw","http://www.dachan.com","894767222"\r\n"1150205","1213","大西洋飲料股份有限公司","大飲","－ ","02","桃園市平鎮區南勢里2鄰南東路410號","35012903","蘇芸樂","洪松輝","蘇芸樂","董事長","洪松輝","(02)2982-0061","19650724","19810410","新台幣                 10.0000元","566226270","0","0","1","大西洋飲料股份有限公司","(02)2982-0061","新北市三重區重陽路三段99號10樓","南台聯合會計師事務所","丁澤祥","蔡玉琴","OCEANIC Bev.","No. 410, Nandong Rd., 2nd Neighborhood, Nanshi Vil., Pingzhen Dist., Taoyuan CTaipei Hsien,Taiwan,R.O.C.","(02)2984-1154","c5012903@ms23.hinet.net","http://applesidra.com.tw","56622627"\r\n"1150205","1215","台灣卜蜂企業股份有限公司","卜蜂","－ ","02","台北市松江路八十七號十七樓","36514783","鄭武樾","許瑞通","劉明哲","特別助理","謝筱芬","02-25077071","19770822","19870727","新台幣                 10.0000元","2947900980","0","0","1","中國信託商業銀行代理部","02-66365566","台北市重慶南路一段八十三號五樓","資誠聯合會計師事務所","廖福銘","蔡蓓華","CPE","17F., No. 87, Songjiang Rd.Taipei City, Taiwan 104","02-25064137","service@cptwn.com.tw","http://www.cptwn.com.tw","294790098"\r\n"1150205","1216","統一企業股份有限公司","統一","－ ","02","71001台南市永康區中正路301號","73251209","羅智先","郭慶峰","陳國煇","財務長","&#20931;忠正","(06)253-2121","19670825","19871228","新台幣                 10.0000元","56820154210","0","0","1","統一綜合證券(股)公司股務代理部","(02)2746-3797","10570台北市松山區東興路8號統一大樓地下室一樓","資誠聯合會計師事務所","田中玉","吳建志","UNI-PRESIDENT","No.301, Zhongzheng Rd., Yongkang Dist.,Tainan City 71001, Taiwan (R.O.C.)","(06)253-2661","jlian@mail.pec.com.tw","https://www.uni-president.com.tw","5682015421"\r\n"1150205","1217","愛之味股份有限公司","愛之味","－ ","02","嘉義縣民雄鄉工業二路11號","65534366","陳冠翰","陳冠豪","陳冠翰","董事長","陳志展 陳冠豪 陳建華","05-2211521-4","19710626","19891028","新台幣                 10.0000元","4945133360","0","0","1","群益金鼎證券股份有限公司","02-27023999","台北市大安區敦化南路二段97號地下二樓","國富浩華聯合會計師事務所","黃鈴雯","李國銘","AGV","NO.11,Kung Yeh Second Rd.,Min Hsiong Industrial ZoneChiayi Hsien,Taiwan","05-2216287","YUEHCHU@mail.agv.com.tw","www.agv.com.tw","494513336"\r\n"1150205","1218","泰山企業股份有限公司","泰山","－ ","02","彰化縣田中鎮興工路6號","59661701","劉偉龍","沈怡君","李淑惠","副總經理","沈怡君","04-8742211","19501026","19891111","新台幣                 10.0000元","4999990380","0","0","1","元大證券股份有限公司","(02)25863117","106045台北市大安區敦化南路二段67號B1","安永聯合會計師事務所","黃子評","林素雯","TAISUN","No.6, Xinggong Rd., Tianzhong Township.Changhua County 520, Taiwan (R.O.C.)","04-8758989","taisunir@taisun.com.tw","www.taisun.com.tw","499999038"\r\n"1150205","1219","福壽實業股份有限公司","福壽","－ ","02","台中市沙鹿區沙田路45號","56192402","洪堯昆","趙文強","徐沛妤","協理","陳祺炆","04-26362111","19550207","19901201","新台幣                 10.0000元","3412383640","0","0","1","凱基證券股份有限公司","02-23892999","100502台北市重慶南路一段2號5樓","群智聯合會計師事務所","張鈞富","吳乾萌","FWUSOW","45,Sha-Tyan,Sha-LuTaichung Taiwan R.O.C","04-26358452","fwusow@fwusow.com.tw","www.fwusow.com.tw","341238364"\r\n"1150205","1220","台榮產業股份有限公司","台榮","－ ","02","台北市中山區南京東路二段206號6樓","03543210","倍安利投資有限公司","陳英凱","周忠平","經理","張大慶","(02)2506-9521","19690313","19911120","新台幣                 10.0000元","1770779440","0","0","1","中國信託商業銀行代理部","(02)66365566","台北市重慶南路一段83號5樓","立本台灣聯合會計師事務所","柯俊輝","張鈞鈞","TAIROUN","6TH FL. NO. 206.  NANKING E. RD., SEC. 2Taipei,Taiwan,ROC","(02)2507-7020","csr@tairoun.com.tw","http://www.tairoun.com.tw/","177077944"\r\n"1150205","1225","福懋油脂股份有限公司","福懋油","－ ","02","台中市大肚區沙田路一段453號","22102298","興泰實業股份有限公司(代表人楊淑樺)","張志賓","秦慧如","財務副總經理","李建儀","25073121","19860418","19930927","新台幣                 10.0000元","2422683060","0","0","1","群益金鼎證券股份有限公司","02-27023999","台北市敦化南路二段97號地下二樓","群智聯合會計師事務所","呂松裕","張鈞富","FOPCO","3RD FL,150 NANJING EAST RD, SEC.2 TAIPEI TAIWAN R.O.CTAIPEI TAIWAN R.O.C.","(02)25071312","cherry.lin@fopco.com.tw","WWW.FOPCO.COM.TW","242268306"\r\n"1150205","1227","佳格食品股份有限公司","佳格","－ ","02","台北市內湖區瑞光路610號10樓","22102473","曹德風","邱子權","曹博睿","執行長","李倍蓮","2709-2323","19860606","19940409","新台幣                 10.0000元","9150895910","0","0","1","中國信託商業銀行代理部","(02)6636-5566","台北市重慶南路一段83號5樓","勤業眾信聯合會計師事務所","方涵妮","陳昭宇","SFC","10F., No. 610, Ruiguang Rd., Neihu Dist.Taipei,Taiwan,R.O.C.","2706-7955","spokesperson1@sfworldwide.com","https://www.sfworldwide.com/","915089591"\r\n"1150205","1229","聯華實業控股股份有限公司","聯華","－ ","02","臺北市南港區南港路一段209號10樓","11996904","苗豐強","林信宏","林信宏","總經理","嚴文卿","(02)2786-1188","19550720","19760719","新台幣                 10.0000元","17959606680","0","0","1","中國信託商業銀行代理部","(02)6636-5566","台北市重慶南路一段83號5樓","安侯建業聯合會計師事務所","許淑敏","郭柔蘭","LHIHC","10F., No. 209, Sec. 1, Nangang Rd., Nangang Dist.,Taipei, Taiwan, R.O.C.","(02)2786-3232","info@lhic.com.tw","https://www.lhicholdings.com/","1795960668"\r\n"1150205","1231","聯華食品工業股份有限公司","聯華食","－ ","02","台北市迪化街一段148號","07569627","李開源","扶兆民","林志遠","財務處協理","陳姵岑","(02)25534546","19700707","19951102","新台幣                 10.0000元","2984544750","0","0","1","永豐金證券股份有限公司","(02)23816288","台北市博愛路17號3樓","勤業眾信聯合會計師事務所","趙永祥","劉明賢","Lian Hwa Foods","148 TI HWA STREET SEC.1,Taipei,Taiwan,R.O.C","(02)25533479","tomlin@lianhwa.com.tw","www.lianhwa.com.tw","298454475"\r\n"1150205","1232","大統益股份有限公司","大統益","－ ","02","台南市官田區二鎮里工業西路32號","20927014","羅智先","陳昭良","陳昭良","總經理","陳冠州","06-698-4500","19820524","19960209","新台幣                 10.0000元","1599749150","0","0","1","統一綜合證券股份有限公司","02-2746-3797","台北市東興路8號地下一樓","資誠聯合會計師事務所","徐惠榆","葉芳婷","TTET","32, Gongye West Road, Erzhen Village, Guantian District, Tainan City, TaiwanTAINAN CITY, TAIWAN","06-698-5530","finance@mail.ttet.com.tw","https://www.ttet.com.tw","159974915"\r\n"1150205","1233","天仁茶業股份有限公司","天仁","－ ","02","台北市忠孝東路4段107號6樓","18559415","李建德","陳中智","王華榮","營運部品牌策略副總","謝艾芸","02-27765580","19751211","19990120","新台幣                 10.0000元","905919480","0","0","1","元大證券股份有限公司","02-25865859","臺北市大安區敦化南路2段67號地下一樓","安永聯合會計師事務所","陳智忠","李育儒","Ten Ren","6F. NO.107,SEC 4, Chung Hsiao East Road,Taipei, Taiwan, ROC","02-27403035","chafortea@tenren.com.tw","http://www.tenren.com.tw/","90591948"\r\n"1150205","1234","黑松股份有限公司","黑松","－ ","02","台北市信義路四段296號3樓","20651901","張斌堂","張智鈞","杜居燦","財務處處長","沈榮宗","(02)2706-2191","19691213","19990312","新台幣                 10.0000元","4018710940","0","0","1","宏遠證券股份有限公司股務代理部","(02)7719-8899","台北市大安區信義路四段236號3樓","勤業眾信聯合會計師事務所","翁博仁","池瑞全","HEY SONG","3RD FL. NO. 296, SEC. 4, HSIN YI RD.TAIPEI, TAIWAN, R.O.C.","(02)2755-2119","heysong@heysong.com.tw","www.heysong.com.tw","401871094"\r\n"1150205","1235","興泰實業股份有限公司","興泰","－ ","02","高雄市仁武區高楠公路10號","85617982","昇鋒投資股份有限公司(代表人楊淑樺)","葉文籐","葉文籐","總經理","王麗雯","07-3425301-5","19721115","20000911","新台幣                 10.0000元","1885778360","0","0","1","國票綜合證券股份有限公司","02-25288988","105411台北市松山區南京東路五段188號15樓","群智聯合會計師事務所","呂松裕會計師","張鈞富會計師","ST","10 KAO-NANG HIGHWAYJEN-WUH KAOHSIUNG TAIWAN R.O.C.","07-3425694","shintailtd@gmail.com","www.goldenbrand.com.tw","188577836"\r\n"1150205","1236","宏亞食品股份有限公司","宏亞","－ ","02","新北市新店區北新路一段86號20樓之6","34106066","張云綺","張云綺","許士彬","總經理特助","許士彬","(02)29180786","19760614","20010917","新台幣                 10.0000元","866740080","0","0","1","福邦證券股份有限公司","(02)2383-6888","台北市中正區忠孝西路一段6號6樓","安永聯合會計師事務所","徐榮煌","劉榮進","Hunya","20F.-6, No.86, Sec. 1, Beixin Rd.,Xindian Dist., New Taipei City 23147","(02)29180706","hunya.com.tw","https://www.hunya.com.tw","86674008"\r\n"1150205","1256","鮮活控股股份有限公司","鮮活果汁-KY","KY 開曼群島                                                    ","02","Suite 102, Cannon Place, P.O. Box 712, North Sound Rd.","37759808","黃國晃","吳明憲","吳明憲","總經理","陳怡如","512-57515501","20100112","20160317","新台幣                 10.0000元","357721600","0","0","1","兆豐證券股份有限公司股務代理部","02-3393-0898","台北市忠孝東路二段95號1樓","勤業眾信聯合會計師事務所","彭以驊","張至誼","Sunjuice","Suite 102, Cannon Place, P.O. Box 712, North Sound Rd.Grand Cayman, KY1-9006","512-57515503","ky@sunjuice.com","https://www.sunjuice.com/","35772160"\r\n"1150205","1301","台灣塑膠工業股份有限公司","台塑","－ ","03","高雄市仁武區水管路100號","75708007","郭文筆","林勝冠","林勝冠","總經理","簡嘉宏","(02)2712-2211","19541105","19640727","新台幣                 10.0000元","63657407810","0","0","1","本公司股務組","(02)2718-9898","台北市內湖區南京東路六段380號10樓","安侯建業聯合會計師事務所","郭欣頤","張肇文","FPC","(A1-11F) No.380, Section 6, Nanjing E. RdTaipei, Taiwan, R.O.C.","(02)2717-8108","formosa@fpc.com.tw","http://www.fpc.com.tw","6365740781"\r\n"1150205","1303","南亞塑膠工業股份有限公司","南亞","－ ","03","台北市內湖區南京東路六段380號(A1)7樓","75370905","吳嘉昭","鄒明仁","鄒明仁","總經理","彭福榮","(02)27122211","19580822","19671115","新台幣                 10.0000元","79308215890","0","0","1","本公司股務組","(02)27189898","台北市內湖區南京東路六段380號10樓","安侯建業聯合會計師事務所","郭欣頤","陳俊光","NPC","7F, No. 380, Sec. 6, Nanjing E. Rd., Neihu Dist., Taipei City(A1)Taipei, Taiwan, R.O.C.","(02)27178533","nanya@npc.com.tw","http://www.npc.com.tw","7930821589"\r\n"1150205","1304","台灣聚合化學品股份有限公司","台聚","－ ","03","台北市內湖區基湖路37號12樓","11917107","吳亦圭","吳培基","吳銘宗","業務副總經理","周澤宜","02-87516888","19650526","19720520","新台幣                 10.0000元","11887635000","0","0","1","本公司股務部","02-26503773","台北市內湖區內湖路一段120巷17號6樓","勤業眾信聯合會計師事務所","陳俊宏","張正修","USI","12TH FLOOR, NO. 37 JI-HU ROAD, NEI-HU DISTRICTTAIPEI 114, TAIWAN, R.O.C.","02-26599524","mtwu@usig.com","www.usife.com.tw","1188763500"\r\n"1150205","1305","華夏海灣塑膠股份有限公司","華夏","－ ","03","台北市內湖區基湖路37號12樓","11686106","吳亦圭","胡吉宏","吳建興","營業處處長","黃俊閔","(02)8751-6888","19640429","19730305","新台幣                 10.0000元","5810504940","0","0","1","本公司股務部","(02)2650-3773","台北市內湖區內湖路一段120巷17號6樓","勤業眾信聯合會計師事務所","張正修","劉怡青","CGPC","12th Floor , NO.37 , Ji-Hu Rd. Nei-Hu DistrictTaipei, Taiwan, R.O.C.","(02)2659-9516","jhwu@usig.com","https://www.cgpc.com.tw","581050494"\r\n"1150205","1307","三芳化學工業股份有限公司","三芳","－ ","03","高雄市三民區通化街120號","83387850","林孟經","林至逸","李禮權","總監","陳偉鉅","(07)3712111","19730616","19851123","新台幣                 10.0000元","3978181260","0","0","1","中國信託代理部","(02)6636-5566","台北市重慶南路一段83號5樓","勤業眾信會計師事務所","王騰葦","劉裕祥","SAN FANG","402 FENGJEN RD.,JENWU SHIANG,KAOSHIUNG,TAIWAN","(07)3711940","jui@sanfang.com.tw","http://www.sanfang.com.tw","397818126"\r\n"1150205","1308","亞洲聚合股份有限公司","亞聚","－ ","03","高雄市林園區工業一路3號","20747385","吳亦圭","吳培基","黃克名","業務處處長","張勝川","(02)8751-6888","19770125","19860620","新台幣                 10.0000元","5937439190","0","0","1","亞洲聚合股份有限公司股務部","(02)2650-3773","台北市內湖區內湖路一段120巷17號6樓","勤業眾信聯合會計師事務所","邱政俊","莊碧玉","APC","NO.3,INDUSTRIAL 1ST RD., LINYUAN DIST.,KAOHSIUNG, TAIWAN, 832 ROC","(02)2659-9553","gltzeng@usig.com","https://www.apc.com.tw/","593743919"\r\n"1150205","1309","台達化學工業股份有限公司","台達化","－ ","03","台北市內湖區基湖路37號12樓","11893409","吳亦圭","吳培基","黃俊豪","協理","陳錫明","(02)8751-6888","19600406","19860627","新台幣                 10.0000元","3975868480","0","0","1","台達化學工業股份有限公司股務部","(02)2650-3773","台北市內湖區內湖路一段120巷17號6樓","勤業眾信聯合會計師事務所","陳俊宏","劉怡青","TTC","12th Floor, No.37, Ji-Hu Rd.,Taipei 114,Taiwan,R.O.C.","(02)2659-9504","chunhao@usig.com","http://www.ttc.com.tw","397586848"\r\n"1150205","1310","台灣苯乙烯工業股份有限公司","台苯","－ ","03","台北市中正區羅斯福路一段六號八樓之一","20844865","林文淵","仲崇國","呂政欣","協理","陳明男","02-23966007","19791116","19870806","新台幣                 10.0000元","5278697640","0","0","1","康和綜合證券股份有限公司","02-8787-1118","台北市信義區基隆路一段176號B1","安侯建業聯合會計師事務所","尹元聖","吳麟","T.S.M.C.","8F-1, No. 6, Sec. 1, Roosevelt Rd., Taipei City , TaiwanTaipei,Taiwan","23960755","investors@mail.smct.com.tw","http://www.smct.com.tw/","527869764"\r\n"1150205","1312","國喬石油化學股份有限公司","國喬","－ ","03","臺北市敦化北路135號8樓","04212250","邱德馨","曾嘉雄","沈美佑","經理","薛鴻敏","(02)2175-4567","19730925","19881221","新台幣                 10.0000元","11266203280","0","20000000","1","凱基證券(股)公司代理部","(02)2389-2999","台北市重慶南路一段2號5 樓","安侯建業聯合會計師事務所","吳政諺","連淑凌","GPPC","8F., No. 135, Dunhua N. Rd., Songshan Dist.,TAIPEI, TAIWAN  R.O.C.","(02)2545-8755","gppc@gppc.com.tw","http://www.gppc.com.tw","1106620328"\r\n"1150205","1313","聯成化學科技股份有限公司","聯成","－ ","03","台北市南港區南港路一段209號A棟9樓","04748660","苗豐強","畢淑蒨","張嘉麟","專案經理","徐桂梅","(02)26517889","19760814","19890327","新台幣                 10.0000元","13308461070","0","0","1","中國信託商業銀行代理部","(02)6636-5566","台北市重慶南路一段83號5F","勤業眾信聯合會計師事務所","劉建良","王儀雯","UPC","9F., Building A, No. 209 NanGang Rd., Sec. 1, NanGang Dist., Taipei, 115,Taiwan, R.O.C","(02)26515818","ir@upc.com.tw","http://www.upc.com.tw","1330846107"\r\n"1150205","1314","中國石油化學工業開發(股)公司","中石化","－ ","03","高雄市大社區經建路1號","03084741","陳瑞隆","陳穎俊(代理)","陳穎俊","總經理(代理)","李建憲、陳台彰","07-3513521","19690708","19910712","新台幣                 10.0000元","37848501300","0","0","1","本公司股務室","02-89782589","台北市松山區東興路12號3樓","安侯建業會計師事務所","吳政諺","李逢暉","CPDC","No. 1, Jingjian Road, Dashe DistrictKaohsiung, Taiwan, R. O. C.","07-3513642","investors@cpdc.com.tw","www.cpdc.com.tw","3784850130"\r\n"1150205","1315","達新工業股份有限公司","達新","－ ","03","台中市西屯區工業區35路51號","51059101","吳子聰","陳以千","賴耿民","副總經理","陳明哲","04-23595511","19661024","19920509","新台幣                 10.0000元","990990000","0","0","1","中國信託商業銀行(股)公司代理部","02-66365566","台北市重慶南路一段83號5樓","國富浩華聯合會計師事務所","王戊昌","林志隆","TAH HSIN","NO.51, 35TH RD.,TAICHUNG INDUSTRIAL PARK ,TAICHUNG ,TAIWAN, R.O.C","04-23595557","thst@mail.tahhsin.com.tw","www.tahhsin.com.tw","99099000"\r\n"1150205","1316","上曜建設開發股份有限公司","上曜","－ ","14","台南市安平區永華路二段248號20樓之6","73654033","張祐銘","曾鵬光","郭育政","財務部副總經理","朱麗娟","(06)2988318","19791211","19921015","新台幣                 10.0000元","3670890190","0","0","1","元大證券股份有限公司","(02)2586-5859","臺北市大安區敦化南路2段67號地下一樓","安侯建業聯合會計師事務所","許振隆","高鈺倫","SUN  YAD","20F.-6, No.248, Sec. 2, Yonghua RdAnping Dist., Tainan City 708, Taiwan","(06)2988311","sunyad_101@yahoo.com.tw","www.sunyad.com.tw","367089019"\r\n"1150205","1319","東陽實業廠股份有限公司","東陽","－ ","12","台南市安和路二段98號","68326665","吳永茂","吳永祥","許芳華","助理副總經理","洪櫻芬","06-3560511","19671030","19941212","新台幣                 10.0000元","5914770680","0","0","1","中國信託商業銀行代理部","02-66365566","台北市重慶南路一段83號5F","安永聯合會計師事務所","胡子仁","洪國森","TYG","98 AN HO ROAD.,SEC,2TAINAN,TAIWAN,R,O,C","06-3566055","15469@tyg.com.tw","WWW.TYG.COM.TW","591477068"\r\n"1150205","1321","大洋塑膠工業股份有限公司","大洋","－ ","03","台北市莒光路310號5,6樓","15024509","陳欽明","陳欽明","邱俊福","經理","鄭有峰","(02)23062131","19650607","19990126","新台幣                 10.0000元","2272282680","0","0","1","凱基證券(股)公司股務代理部","(02)23148800","台北市重慶南路一段2號5樓","安侯建業聯合會計師事務所","余聖河","羅瑞芝","OPC","5F,310 CHUKWANG ROADTAIPEI,TAIWAN,R.O.C","(02)23027464","mauwau@opc.com.tw","www.opc.com.tw","227228268"\r\n"1150205","1323","永裕塑膠工業股份有限公司","永裕","－ ","03","台南市仁德區勝利路88號","68192103","王威程","王威程","郭錦添","副總經理","蔡崇誠","06-2793711","19730402","20000911","新台幣                 10.0000元","912745540","0","0","1","凱基證券股份有限公司","02-23892999","台北市重慶南路一段2號5樓","資誠聯合會計師事務所","葉芳婷","徐惠榆","YONYU","88 SHENG LI ROAD,RENDE  DISTRICT,TAINAN,TAIWANTainan ,Taiwan","06-2705088","kct3232@yonyu.com.tw","www.yonyu.com.tw","91274554"\r\n"1150205","1324","地球綜合工業股份有限公司","地球","－ ","03","台北市中山區南京東路3段61號7樓","07147916","鈞鼎投資股份有限公司(代表人張德照)","黃林慶","張雅琪","財務部部長","曾嬿妤","(02)2506-6666","19641208","20000911","新台幣                 10.0000元","751218820","0","0","1","永豐金證券股份有限公司","02-23816288","台北市中正區博愛路17號3樓","安永聯合會計師事務所","徐榮煌","楊弘斌","GLOBE TAPE","7F.NO.61.SECTION 3,NANKING E ROADTAIPEI TAIWAN R.O.C.","(02)2507-0226","ir@globetape.com.tw","https://www.globetape.com","75121882"\r\n"1150205","1325","恒大股份有限公司","恆大","－ ","03","台北市林森北路372號10樓","11455800","黃美慧","黃美慧","周壽祿","協理","廖淑姬","(02)25119161","19621014","20000911","新台幣                 10.0000元","852811980","0","0","1","中國信託商業銀行代理部","(02)66365566","台北市重慶南路一段83號5樓","勤業眾信聯合會計師事務所","薛峻泯","陳昭伶","UK","10F, 372, LIN SHEN N. ROADTAIPEI, TAIWAN, R.O.C.","(02)25374473","uk4409@ms34.hinet.net","www.uk.com.tw","85281198"\r\n"1150205","1326","台灣化學纖維股份有限公司","台化","－ ","03","彰化市中山路3段359號","58650902","洪福源","呂文進","呂文進","總經理","黃國賢","(02)27122211","19650305","19841220","新台幣                 10.0000元","58611862910","0","0","1","台灣化學纖維股份有限公司股務室","(02)27189898","台北市內湖區南京東路六段380號10樓","資誠聯合會計師事務所","阮呂曼玉","徐聖忠","FCFC","10F., No.388, Sec.6, Nanjing E. Rd.Taipei, Taiwan, R.O.C","(02)27133229","fcfc@fcfc.com.tw","http://www.fcfc.com.tw","5861186291"\r\n"1150205","1337","亞洲塑膠再生資源控股有限公司","再生-KY","KY 開曼群島                                                    ","03","高雄市苓雅區四維四路190號12樓之2",

'\ufeff出表日期,公司代號,公司名稱,公司簡稱,外國企業註冊地國,產業別,住址,營利事業統一編號,董事長,總經理,發言人,發言人職稱,代理發言人,總機電話,成立日期,上市日期,普通股每股面額,實收資本額,私募股數,特別股,編制財務報表類型,股票過戶機構,過戶電話,過戶地址,簽證會計師事務所,簽證會計師1,簽證會計師2,英文簡稱,英文通訊地址,傳真機號碼,電子郵件信箱,網址,已發行普通股數或TDR原股發行股數\r\n"1150205","1101","臺灣水泥股份有限公司","台泥","－ ","01","台北市中山北路2段113號","11913502","張安平","程耀輝","葉毓君","永續長","賴家柔","(02)2531-7099","19501229","19620209","新台幣                 10.0000元","77511817420","0","200000000","1","中國信託商業銀行代理部","66365566","台北市重慶南路一段83號5樓","勤業眾信聯合會計師事務所","翁雅玲","黃惠敏","TCC","No.113, Sec.2, Zhongshan N. Rd.,Taipei City 104,Taiwan (R.O.C.)","(02)2531-6529","finance@taiwancement.com","https://www.tccgroupholdings.com/tw/","7551181742"\r\n"1150205","1102","亞洲水泥股份有限公司","亞泥","－ ","01","台北市大安區敦化南路2段207號30、31樓","03244509","徐旭東","李坤炎","王照宇","協理","楊淯玲","02-2733-8000","19570321","19620608","新台幣                 10.0000元","35465628810","0","0","1","亞東證券股份有限公司","02-7753-1699","新北市板橋區新站路16號13樓","勤業眾信聯合會計師事務所","戴信維","池瑞全","ACC","30-31F., No.207, Sec. 2, Dunhua S. Rd., Da\' an Dist., Taipei City 106, TaiwanTAIPEI,TAIWAN,R.O.C","02-2736-6263","service@acc.com.tw","www.acc.com.tw","3546562881"\r\n"1150205","1103","嘉新水泥股份有限公司","嘉泥","－ ","01","台北市中山北路二段96號","11892801","張剛綸","王立心","金哲毅","董事會秘書室資深經理","馮文裕","(02)2551-5211","19541213","19691114","新台幣                 10.0000元","7902474590","0","0","1","群益金鼎證券股份有限公司股代部","(02)2702-3999","台北市敦化南路2段97號地下2樓","勤業眾信聯合會計師事務所","陳薔旬","梁盛泰","CHC","No.96, Sec. 2, Zhongshan N. Rd., Zhongshan Dist.Taipei City 10449, Taiwan (R.O.C.)","(02)2511-4002","ir@chcgroup.com.tw","www.chcgroup.com.tw","790247459"\r\n"1150205","1104","環球水泥股份有限公司","環泥","－ ","01","台北市南京東路二段125號10樓","07568009","博智投資股份有限公司","侯智升","楊宗仁","副總經理","高琮堯","02-25077801","19600321","19710201","新台幣                 10.0000元","6866818160","0","0","1","永豐金證券股份有限公司","02-23816288","台北市博愛路17號3樓","勤業眾信聯合會計師事務所","李季珍","廖鴻儒","UCC","10th F., 125 Nanking E.Rd Sec. 2,Taipei Taiwan","02-25075870","ucc@ucctw.com","www.ucctw.com","686681816"\r\n"1150205","1108","幸福水泥股份有限公司","幸福","－ ","01","台北市松江路237號15樓","40601248","陳韻如","陳明賢","溫秀菊","財務部經理","陳一誠","25092188","19740507","19900606","新台幣                 10.0000元","4047380490","0","0","1","永豐金證券股務代理","2381-6288","台北市中正區博愛路17號3樓","勤業眾信聯合會計師事務所","陳招美","陳薔旬","LUCKY CEMENT","15TH FL.,NO.237,SUNG KIANG RD.,TAIPEI,TAIWAN,R.O.C.","25048672","wendy@luckygrp.com.tw","www.luckygrp.com.tw","404738049"\r\n"1150205","1109","信大水泥股份有限公司","信大","－ ","01","台北市寶慶路37號7樓","03279507","楊智雄","楊大寬","張清壽","資深協理","蔡素秋","(02)23816731","19640315","19911205","新台幣                 10.0000元","3411588680","0","0","1","中國信託商業銀行代理部","(02)6636-5566","台北巿重慶南路一段83號5樓","資誠聯合會計師事務所","李秀玲","支秉鈞","HsingTa","No. 37, 7F, Baoqing Rd.,Taipei City 100, Taiwan (R.O.C.)","23314086","service@hsingta.com.tw","www.hsingta.com.tw","341158868"\r\n"1150205","1110","東南水泥股份有限公司","東泥","－ ","01","高雄市前金區五福三路21號4樓之1","83078600","陳敏斷","吳炎輝","黃薪翰","財務部副總經理","唐榮宗","07-2711121","19561228","19941022","新台幣                 10.0000元","5720007970","0","0","1","元大證券股份有限公司","02-25865859","臺北市大安區敦化南路2段67號地下一樓","國富浩華聯合會計師事務所","黃致富","黃鈴雯","SE CEMENT","NO.21 Wu Fu 3 RoadKaohsiung, Taiwan, R.O.C.","07-9505895","southeast@secement.com","www.southeastcement.com.tw","572000797"\r\n"1150205","1201","味全食品工業股份有限公司","味全","－ ","02","台北市松江路125號","11347802","徐文芳","滕以勇","李文學","財務長","待補","(02)25065020","19530922","19620209","新台幣                 10.0000元","5060629140","0","0","1","元大證券股務代理部","(02)25865859","臺北市大安區敦化南路2段67號地下一樓","資誠聯合會計師事務所","黃世鈞","葉翠苗","WEI CHUAN","10F., No.125, Sung Chiang Rd.Taipei, Taiwan, R.O.C.","(02)25063182","service@weichuan.com.tw","https://www.weichuan.com.tw","506062914"\r\n"1150205","1203","味王股份有限公司","味王","－ ","02","台北市中山北路二段79號5樓","07067309","陳清福","陳恭平","魏璟雄","協理","李兆弘","(02)25717271","19590704","19640824","新台幣                 10.0000元","2400000000","0","0","1","群益金鼎證券股份有限公司","27023999","台北市敦化南路二段97號地下2樓","大中國際聯合會計師事務所","溫明郁","張卉諭","VE WONG","5TH FL., 79 CHUNG SHAN N. RD., SEC.2TAIPEI TAIWAN","(02)25811006","wei@vewong.com.tw","https://www.vewong.com/","240000000"\r\n"1150205","1210","大成長城企業股份有限公司","大成","－ ","02","台南市永康區蔦松二街三號","73008303","韓家宇","韓芳豪","夏銜譽","副總經理","許博涵","06-2531111","19601228","19780520","新台幣                 10.0000元","8947672220","0","0","1","中國信託商業銀行代理部","02-66365566","台北市重慶南路一段八十三號六樓","安侯建業會計師事務所","李逢暉","蔡佩汝","GREATWALL","3 NIAOSUN 2TH STREETYONGKONG TAINAN CONTY TAIWAN","06-2534596","ir@ms.greatwall.com.tw","http://www.dachan.com","894767222"\r\n"1150205","1213","大西洋飲料股份有限公司","大飲","－ ","02","桃園市平鎮區南勢里2鄰南東路410號","35012903","蘇芸樂","洪松輝","蘇芸樂","董事長","洪松輝","(02)2982-0061","19650724","19810410","新台幣                 10.0000元","566226270","0","0","1","大西洋飲料股份有限公司","(02)2982-0061","新北市三重區重陽路三段99號10樓","南台聯合會計師事務所","丁澤祥","蔡玉琴","OCEANIC Bev.","No. 410, Nandong Rd., 2nd Neighborhood, Nanshi Vil., Pingzhen Dist., Taoyuan CTaipei Hsien,Taiwan,R.O.C.","(02)2984-1154","c5012903@ms23.hinet.net","http://applesidra.com.tw","56622627"\r\n"1150205","1215","台灣卜蜂企業股份有限公司","卜蜂","－ ","02","台北市松江路八十七號十七樓","36514783","鄭武樾","許瑞通","劉明哲","特別助理","謝筱芬","02-25077071","19770822","19870727","新台幣                 10.0000元","2947900980","0","0","1","中國信託商業銀行代理部","02-66365566","台北市重慶南路一段八十三號五樓","資誠聯合會計師事務所","廖福銘","蔡蓓華","CPE","17F., No. 87, Songjiang Rd.Taipei City, Taiwan 104","02-25064137","service@cptwn.com.tw","http://www.cptwn.com.tw","294790098"\r\n"1150205","1216","統一企業股份有限公司","統一","－ ","02","71001台南市永康區中正路301號","73251209","羅智先","郭慶峰","陳國煇","財務長","&#20931;忠正","(06)253-2121","19670825","19871228","新台幣                 10.0000元","56820154210","0","0","1","統一綜合證券(股)公司股務代理部","(02)2746-3797","10570台北市松山區東興路8號統一大樓地下室一樓","資誠聯合會計師事務所","田中玉","吳建志","UNI-PRESIDENT","No.301, Zhongzheng Rd., Yongkang Dist.,Tainan City 71001, Taiwan (R.O.C.)","(06)253-2661","jlian@mail.pec.com.tw","https://www.uni-president.com.tw","5682015421"\r\n"1150205","1217","愛之味股份有限公司","愛之味","－ ","02","嘉義縣民雄鄉工業二路11號","65534366","陳冠翰","陳冠豪","陳冠翰","董事長","陳志展 陳冠豪 陳建華","05-2211521-4","19710626","19891028","新台幣                 10.0000元","4945133360","0","0","1","群益金鼎證券股份有限公司","02-27023999","台北市大安區敦化南路二段97號地下二樓","國富浩華聯合會計師事務所","黃鈴雯","李國銘","AGV","NO.11,Kung Yeh Second Rd.,Min Hsiong Industrial ZoneChiayi Hsien,Taiwan","05-2216287","YUEHCHU@mail.agv.com.tw","www.agv.com.tw","494513336"\r\n"1150205","1218","泰山企業股份有限公司","泰山","－ ","02","彰化縣田中鎮興工路6號","59661701","劉偉龍","沈怡君","李淑惠","副總經理","沈怡君","04-8742211","19501026","19891111","新台幣                 10.0000元","4999990380","0","0","1","元大證券股份有限公司","(02)25863117","106045台北市大安區敦化南路二段67號B1","安永聯合會計師事務所","黃子評","林素雯","TAISUN","No.6, Xinggong Rd., Tianzhong Township.Changhua County 520, Taiwan (R.O.C.)","04-8758989","taisunir@taisun.com.tw","www.taisun.com.tw","499999038"\r\n"1150205","1219","福壽實業股份有限公司","福壽","－ ","02","台中市沙鹿區沙田路45號","56192402","洪堯昆","趙文強","徐沛妤","協理","陳祺炆","04-26362111","19550207","19901201","新台幣                 10.0000元","3412383640","0","0","1","凱基證券股份有限公司","02-23892999","100502台北市重慶南路一段2號5樓","群智聯合會計師事務所","張鈞富","吳乾萌","FWUSOW","45,Sha-Tyan,Sha-LuTaichung Taiwan R.O.C","04-26358452","fwusow@fwusow.com.tw","www.fwusow.com.tw","341238364"\r\n"1150205","1220","台榮產業股份有限公司","台榮","－ ","02","台北市中山區南京東路二段206號6樓","03543210","倍安利投資有限公司","陳英凱","周忠平","經理","張大慶","(02)2506-9521","19690313","19911120","新台幣                 10.0000元","1770779440","0","0","1","中國信託商業銀行代理部","(02)66365566","台北市重慶南路一段83號5樓","立本台灣聯合會計師事務所","柯俊輝","張鈞鈞","TAIROUN","6TH FL. NO. 206.  NANKING E. RD., SEC. 2Taipei,Taiwan,ROC","(02)2507-7020","csr@tairoun.com.tw","http://www.tairoun.com.tw/","177077944"\r\n"1150205","1225","福懋油脂股份有限公司","福懋油","－ ","02","台中市大肚區沙田路一段453號","22102298","興泰實業股份有限公司(代表人楊淑樺)","張志賓","秦慧如","財務副總經理","李建儀","25073121","19860418","19930927","新台幣                 10.0000元","2422683060","0","0","1","群益金鼎證券股份有限公司","02-27023999","台北市敦化南路二段97號地下二樓","群智聯合會計師事務所","呂松裕","張鈞富","FOPCO","3RD FL,150 NANJING EAST RD, SEC.2 TAIPEI TAIWAN R.O.CTAIPEI TAIWAN R.O.C.","(02)25071312","cherry.lin@fopco.com.tw","WWW.FOPCO.COM.TW","242268306"\r\n"1150205","1227","佳格食品股份有限公司","佳格","－ ","02","台北市內湖區瑞光路610號10樓","22102473","曹德風","邱子權","曹博睿","執行長","李倍蓮","2709-2323","19860606","19940409","新台幣                 10.0000元","9150895910","0","0","1","中國信託商業銀行代理部","(02)6636-5566","台北市重慶南路一段83號5樓","勤業眾信聯合會計師事務所","方涵妮","陳昭宇","SFC","10F., No. 610, Ruiguang Rd., Neihu Dist.Taipei,Taiwan,R.O.C.","2706-7955","spokesperson1@sfworldwide.com","https://www.sfworldwide.com/","915089591"\r\n"1150205","1229","聯華實業控股股份有限公司","聯華","－ ","02","臺北市南港區南港路一段209號10樓","11996904","苗豐強","林信宏","林信宏","總經理","嚴文卿","(02)2786-1188","19550720","19760719","新台幣                 10.0000元","17959606680","0","0","1","中國信託商業銀行代理部","(02)6636-5566","台北市重慶南路一段83號5樓","安侯建業聯合會計師事務所","許淑敏","郭柔蘭","LHIHC","10F., No. 209, Sec. 1, Nangang Rd., Nangang Dist.,Taipei, Taiwan, R.O.C.","(02)2786-3232","info@lhic.com.tw","https://www.lhicholdings.com/","1795960668"\r\n"1150205","1231","聯華食品工業股份有限公司","聯華食","－ ","02","台北市迪化街一段148號","07569627","李開源","扶兆民","林志遠","財務處協理","陳姵岑","(02)25534546","19700707","19951102","新台幣                 10.0000元","2984544750","0","0","1","永豐金證券股份有限公司","(02)23816288","台北市博愛路17號3樓","勤業眾信聯合會計師事務所","趙永祥","劉明賢","Lian Hwa Foods","148 TI HWA STREET SEC.1,Taipei,Taiwan,R.O.C","(02)25533479","tomlin@lianhwa.com.tw","www.lianhwa.com.tw","298454475"\r\n"1150205","1232","大統益股份有限公司","大統益","－ ","02","台南市官田區二鎮里工業西路32號","20927014","羅智先","陳昭良","陳昭良","總經理","陳冠州","06-698-4500","19820524","19960209","新台幣                 10.0000元","1599749150","0","0","1","統一綜合證券股份有限公司","02-2746-3797","台北市東興路8號地下一樓","資誠聯合會計師事務所","徐惠榆","葉芳婷","TTET","32, Gongye West Road, Erzhen Village, Guantian District, Tainan City, TaiwanTAINAN CITY, TAIWAN","06-698-5530","finance@mail.ttet.com.tw","https://www.ttet.com.tw","159974915"\r\n"1150205","1233","天仁茶業股份有限公司","天仁","－ ","02","台北市忠孝東路4段107號6樓","18559415","李建德","陳中智","王華榮","營運部品牌策略副總","謝艾芸","02-27765580","19751211","19990120","新台幣                 10.0000元","905919480","0","0","1","元大證券股份有限公司","02-25865859","臺北市大安區敦化南路2段67號地下一樓","安永聯合會計師事務所","陳智忠","李育儒","Ten Ren","6F. NO.107,SEC 4, Chung Hsiao East Road,Taipei, Taiwan, ROC","02-27403035","chafortea@tenren.com.tw","http://www.tenren.com.tw/","90591948"\r\n"1150205","1234","黑松股份有限公司","黑松","－ ","02","台北市信義路四段296號3樓","20651901","張斌堂","張智鈞","杜居燦","財務處處長","沈榮宗","(02)2706-2191","19691213","19990312","新台幣                 10.0000元","4018710940","0","0","1","宏遠證券股份有限公司股務代理部","(02)7719-8899","台北市大安區信義路四段236號3樓","勤業眾信聯合會計師事務所","翁博仁","池瑞全","HEY SONG","3RD FL. NO. 296, SEC. 4, HSIN YI RD.TAIPEI, TAIWAN, R.O.C.","(02)2755-2119","heysong@heysong.com.tw","www.heysong.com.tw","401871094"\r\n"1150205","1235","興泰實業股份有限公司","興泰","－ ","02","高雄市仁武區高楠公路10號","85617982","昇鋒投資股份有限公司(代表人楊淑樺)","葉文籐","葉文籐","總經理","王麗雯","07-3425301-5","19721115","20000911","新台幣                 10.0000元","1885778360","0","0","1","國票綜合證券股份有限公司","02-25288988","105411台北市松山區南京東路五段188號15樓","群智聯合會計師事務所","呂松裕會計師","張鈞富會計師","ST","10 KAO-NANG HIGHWAYJEN-WUH KAOHSIUNG TAIWAN R.O.C.","07-3425694","shintailtd@gmail.com","www.goldenbrand.com.tw","188577836"\r\n"1150205","1236","宏亞食品股份有限公司","宏亞","－ ","02","新北市新店區北新路一段86號20樓之6","34106066","張云綺","張云綺","許士彬","總經理特助","許士彬","(02)29180786","19760614","20010917","新台幣                 10.0000元","866740080","0","0","1","福邦證券股份有限公司","(02)2383-6888","台北市中正區忠孝西路一段6號6樓","安永聯合會計師事務所","徐榮煌","劉榮進","Hunya","20F.-6, No.86, Sec. 1, Beixin Rd.,Xindian Dist., New Taipei City 23147","(02)29180706","hunya.com.tw","https://www.hunya.com.tw","86674008"\r\n"1150205","1256","鮮活控股股份有限公司","鮮活果汁-KY","KY 開曼群島                                                    ","02","Suite 102, Cannon Place, P.O. Box 712, North Sound Rd.","37759808","黃國晃","吳明憲","吳明憲","總經理","陳怡如","512-57515501","20100112","20160317","新台幣                 10.0000元","357721600","0","0","1","兆豐證券股份有限公司股務代理部","02-3393-0898","台北市忠孝東路二段95號1樓","勤業眾信聯合會計師事務所","彭以驊","張至誼","Sunjuice","Suite 102, Cannon Place, P.O. Box 712, North Sound Rd.Grand Cayman, KY1-9006","512-57515503","ky@sunjuice.com","https://www.sunjuice.com/","35772160"\r\n"1150205","1301","台灣塑膠工業股份有限公司","台塑","－ ","03","高雄市仁武區水管路100號","75708007","郭文筆","林勝冠","林勝冠","總經理","簡嘉宏","(02)2712-2211","19541105","19640727","新台幣                 10.0000元","63657407810","0","0","1","本公司股務組","(02)2718-9898","台北市內湖區南京東路六段380號10樓","安侯建業聯合會計師事務所","郭欣頤","張肇文","FPC","(A1-11F) No.380, Section 6, Nanjing E. RdTaipei, Taiwan, R.O.C.","(02)2717-8108","formosa@fpc.com.tw","http://www.fpc.com.tw","6365740781"\r\n"1150205","1303","南亞塑膠工業股份有限公司","南亞","－ ","03","台北市內湖區南京東路六段380號(A1)7樓","75370905","吳嘉昭","鄒明仁","鄒明仁","總經理","彭福榮","(02)27122211","19580822","19671115","新台幣                 10.0000元","79308215890","0","0","1","本公司股務組","(02)27189898","台北市內湖區南京東路六段380號10樓","安侯建業聯合會計師事務所","郭欣頤","陳俊光","NPC","7F, No. 380, Sec. 6, Nanjing E. Rd., Neihu Dist., Taipei City(A1)Taipei, Taiwan, R.O.C.","(02)27178533","nanya@npc.com.tw","http://www.npc.com.tw","7930821589"\r\n"1150205","1304","台灣聚合化學品股份有限公司","台聚","－ ","03","台北市內湖區基湖路37號12樓","11917107","吳亦圭","吳培基","吳銘宗","業務副總經理","周澤宜","02-87516888","19650526","19720520","新台幣                 10.0000元","11887635000","0","0","1","本公司股務部","02-26503773","台北市內湖區內湖路一段120巷17號6樓","勤業眾信聯合會計師事務所","陳俊宏","張正修","USI","12TH FLOOR, NO. 37 JI-HU ROAD, NEI-HU DISTRICTTAIPEI 114, TAIWAN, R.O.C.","02-26599524","mtwu@usig.com","www.usife.com.tw","1188763500"\r\n"1150205","1305","華夏海灣塑膠股份有限公司","華夏","－ ","03","台北市內湖區基湖路37號12樓","11686106","吳亦圭","胡吉宏","吳建興","營業處處長","黃俊閔","(02)8751-6888","19640429","19730305","新台幣                 10.0000元","5810504940","0","0","1","本公司股務部","(02)2650-3773","台北市內湖區內湖路一段120巷17號6樓","勤業眾信聯合會計師事務所","張正修","劉怡青","CGPC","12th Floor , NO.37 , Ji-Hu Rd. Nei-Hu DistrictTaipei, Taiwan, R.O.C.","(02)2659-9516","jhwu@usig.com","https://www.cgpc.com.tw","581050494"\r\n"1150205","1307","三芳化學工業股份有限公司","三芳","－ ","03","高雄市三民區通化街120號","83387850","林孟經","林至逸","李禮權","總監","陳偉鉅","(07)3712111","19730616","19851123","新台幣                 10.0000元","3978181260","0","0","1","中國信託代理部","(02)6636-5566","台北市重慶南路一段83號5樓","勤業眾信會計師事務所","王騰葦","劉裕祥","SAN FANG","402 FENGJEN RD.,JENWU SHIANG,KAOSHIUNG,TAIWAN","(07)3711940","jui@sanfang.com.tw","http://www.sanfang.com.tw","397818126"\r\n"1150205","1308","亞洲聚合股份有限公司","亞聚","－ ","03","高雄市林園區工業一路3號","20747385","吳亦圭","吳培基","黃克名","業務處處長","張勝川","(02)8751-6888","19770125","19860620","新台幣                 10.0000元","5937439190","0","0","1","亞洲聚合股份有限公司股務部","(02)2650-3773","台北市內湖區內湖路一段120巷17號6樓","勤業眾信聯合會計師事務所","邱政俊","莊碧玉","APC","NO.3,INDUSTRIAL 1ST RD., LINYUAN DIST.,KAOHSIUNG, TAIWAN, 832 ROC","(02)2659-9553","gltzeng@usig.com","https://www.apc.com.tw/","593743919"\r\n"1150205","1309","台達化學工業股份有限公司","台達化","－ ","03","台北市內湖區基湖路37號12樓","11893409","吳亦圭","吳培基","黃俊豪","協理","陳錫明","(02)8751-6888","19600406","19860627","新台幣                 10.0000元","3975868480","0","0","1","台達化學工業股份有限公司股務部","(02)2650-3773","台北市內湖區內湖路一段120巷17號6樓","勤業眾信聯合會計師事務所","陳俊宏","劉怡青","TTC","12th Floor, No.37, Ji-Hu Rd.,Taipei 114,Taiwan,R.O.C.","(02)2659-9504","chunhao@usig.com","http://www.ttc.com.tw","397586848"\r\n"1150205","1310","台灣苯乙烯工業股份有限公司","台苯","－ ","03","台北市中正區羅斯福路一段六號八樓之一","20844865","林文淵","仲崇國","呂政欣","協理","陳明男","02-23966007","19791116","19870806","新台幣                 10.0000元","5278697640","0","0","1","康和綜合證券股份有限公司","02-8787-1118","台北市信義區基隆路一段176號B1","安侯建業聯合會計師事務所","尹元聖","吳麟","T.S.M.C.","8F-1, No. 6, Sec. 1, Roosevelt Rd., Taipei City , TaiwanTaipei,Taiwan","23960755","investors@mail.smct.com.tw","http://www.smct.com.tw/","527869764"\r\n"1150205","1312","國喬石油化學股份有限公司","國喬","－ ","03","臺北市敦化北路135號8樓","04212250","邱德馨","曾嘉雄","沈美佑","經理","薛鴻敏","(02)2175-4567","19730925","19881221","新台幣                 10.0000元","11266203280","0","20000000","1","凱基證券(股)公司代理部","(02)2389-2999","台北市重慶南路一段2號5 樓","安侯建業聯合會計師事務所","吳政諺","連淑凌","GPPC","8F., No. 135, Dunhua N. Rd., Songshan Dist.,TAIPEI, TAIWAN  R.O.C.","(02)2545-8755","gppc@gppc.com.tw","http://www.gppc.com.tw","1106620328"\r\n"1150205","1313","聯成化學科技股份有限公司","聯成","－ ","03","台北市南港區南港路一段209號A棟9樓","04748660","苗豐強","畢淑蒨","張嘉麟","專案經理","徐桂梅","(02)26517889","19760814","19890327","新台幣                 10.0000元","13308461070","0","0","1","中國信託商業銀行代理部","(02)6636-5566","台北市重慶南路一段83號5F","勤業眾信聯合會計師事務所","劉建良","王儀雯","UPC","9F., Building A, No. 209 NanGang Rd., Sec. 1, NanGang Dist., Taipei, 115,Taiwan, R.O.C","(02)26515818","ir@upc.com.tw","http://www.upc.com.tw","1330846107"\r\n"1150205","1314","中國石油化學工業開發(股)公司","中石化","－ ","03","高雄市大社區經建路1號","03084741","陳瑞隆","陳穎俊(代理)","陳穎俊","總經理(代理)","李建憲、陳台彰","07-3513521","19690708","19910712","新台幣                 10.0000元","37848501300","0","0","1","本公司股務室","02-89782589","台北市松山區東興路12號3樓","安侯建業會計師事務所","吳政諺","李逢暉","CPDC","No. 1, Jingjian Road, Dashe DistrictKaohsiung, Taiwan, R. O. C.","07-3513642","investors@cpdc.com.tw","www.cpdc.com.tw","3784850130"\r\n"1150205","1315","達新工業股份有限公司","達新","－ ","03","台中市西屯區工業區35路51號","51059101","吳子聰","陳以千","賴耿民","副總經理","陳明哲","04-23595511","19661024","19920509","新台幣                 10.0000元","990990000","0","0","1","中國信託商業銀行(股)公司代理部","02-66365566","台北市重慶南路一段83號5樓","國富浩華聯合會計師事務所","王戊昌","林志隆","TAH HSIN","NO.51, 35TH RD.,TAICHUNG INDUSTRIAL PARK ,TAICHUNG ,TAIWAN, R.O.C","04-23595557","thst@mail.tahhsin.com.tw","www.tahhsin.com.tw","99099000"\r\n"1150205","1316","上曜建設開發股份有限公司","上曜","－ ","14","台南市安平區永華路二段248號20樓之6","73654033","張祐銘","曾鵬光","郭育政","財務部副總經理","朱麗娟","(06)2988318","19791211","19921015","新台幣                 10.0000元","3670890190","0","0","1","元大證券股份有限公司","(02)2586-5859","臺北市大安區敦化南路2段67號地下一樓","安侯建業聯合會計師事務所","許振隆","高鈺倫","SUN  YAD","20F.-6, No.248, Sec. 2, Yonghua RdAnping Dist., Tainan City 708, Taiwan","(06)2988311","sunyad_101@yahoo.com.tw","www.sunyad.com.tw","367089019"\r\n"1150205","1319","東陽實業廠股份有限公司","東陽","－ ","12","台南市安和路二段98號","68326665","吳永茂","吳永祥","許芳華","助理副總經理","洪櫻芬","06-3560511","19671030","19941212","新台幣                 10.0000元","5914770680","0","0","1","中國信託商業銀行代理部","02-66365566","台北市重慶南路一段83號5F","安永聯合會計師事務所","胡子仁","洪國森","TYG","98 AN HO ROAD.,SEC,2TAINAN,TAIWAN,R,O,C","06-3566055","15469@tyg.com.tw","WWW.TYG.COM.TW","591477068"\r\n"1150205","1321","大洋塑膠工業股份有限公司","大洋","－ ","03","台北市莒光路310號5,6樓","15024509","陳欽明","陳欽明","邱俊福","經理","鄭有峰","(02)23062131","19650607","19990126","新台幣                 10.0000元","2272282680","0","0","1","凱基證券(股)公司股務代理部","(02)23148800","台北市重慶南路一段2號5樓","安侯建業聯合會計師事務所","余聖河","羅瑞芝","OPC","5F,310 CHUKWANG ROADTAIPEI,TAIWAN,R.O.C","(02)23027464","mauwau@opc.com.tw","www.opc.com.tw","227228268"\r\n"1150205","1323","永裕塑膠工業股份有限公司","永裕","－ ","03","台南市仁德區勝利路88號","68192103","王威程","王威程","郭錦添","副總經理","蔡崇誠","06-2793711","19730402","20000911","新台幣                 10.0000元","912745540","0","0","1","凱基證券股份有限公司","02-23892999","台北市重慶南路一段2號5樓","資誠聯合會計師事務所","葉芳婷","徐惠榆","YONYU","88 SHENG LI ROAD,RENDE  DISTRICT,TAINAN,TAIWANTainan ,Taiwan","06-2705088","kct3232@yonyu.com.tw","www.yonyu.com.tw","91274554"\r\n"1150205","1324","地球綜合工業股份有限公司","地球","－ ","03","台北市中山區南京東路3段61號7樓","07147916","鈞鼎投資股份有限公司(代表人張德照)","黃林慶","張雅琪","財務部部長","曾嬿妤","(02)2506-6666","19641208","20000911","新台幣                 10.0000元","751218820","0","0","1","永豐金證券股份有限公司","02-23816288","台北市中正區博愛路17號3樓","安永聯合會計師事務所","徐榮煌","楊弘斌","GLOBE TAPE","7F.NO.61.SECTION 3,NANKING E ROADTAIPEI TAIWAN R.O.C.","(02)2507-0226","ir@globetape.com.tw","https://www.globetape.com","75121882"\r\n"1150205","1325","恒大股份有限公司","恆大","－ ","03","台北市林森北路372號10樓","11455800","黃美慧","黃美慧","周壽祿","協理","廖淑姬","(02)25119161","19621014","20000911","新台幣                 10.0000元","852811980","0","0","1","中國信託商業銀行代理部","(02)66365566","台北市重慶南路一段83號5樓","勤業眾信聯合會計師事務所","薛峻泯","陳昭伶","UK","10F, 372, LIN SHEN N. ROADTAIPEI, TAIWAN, R.O.C.","(02)25374473","uk4409@ms34.hinet.net","www.uk.com.tw","85281198"\r\n"1150205","1326","台灣化學纖維股份有限公司","台化","－ ","03","彰化市中山路3段359號","58650902","洪福源","呂文進","呂文進","總經理","黃國賢","(02)27122211","19650305","19841220","新台幣                 10.0000元","58611862910","0","0","1","台灣化學纖維股份有限公司股務室","(02)27189898","台北市內湖區南京東路六段380號10樓","資誠聯合會計師事務所","阮呂曼玉","徐聖忠","FCFC","10F., No.388, Sec.6, Nanjing E. Rd.Taipei, Taiwan, R.O.C","(02)27133229","fcfc@fcfc.com.tw","http://www.fcfc.com.tw","5861186291"\r\n"1150205","1337","亞洲塑膠再生資源控股有限公司","再生-KY","KY 開曼群島                                                    ","03","高雄市苓雅區四維四路190號12樓之2",

In [5]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [6]:
df_listing

0       ﻿出表日期    公司代號                            公司名稱      公司簡稱  \
0     1150205    1101                      臺灣水泥股份有限公司        台泥
1     1150205    1102                      亞洲水泥股份有限公司        亞泥
2     1150205    1103                      嘉新水泥股份有限公司        嘉泥
3     1150205    1104                      環球水泥股份有限公司        環泥
4     1150205    1108                      幸福水泥股份有限公司        幸福
5     1150205    1109                      信大水泥股份有限公司        信大
6     1150205    1110                      東南水泥股份有限公司        東泥
7     1150205    1201                    味全食品工業股份有限公司        味全
8     1150205    1203                        味王股份有限公司        味王
9     1150205    1210                    大成長城企業股份有限公司        大成
10    1150205    1213                     大西洋飲料股份有限公司        大飲
11    1150205    1215                    台灣卜蜂企業股份有限公司        卜蜂
12    1150205    1216                      統一企業股份有限公司        統一
13    1150205    1217                       愛之味股份有限公司       愛之味
14    1150205    1218                      泰山企業股份有限公司        泰山
15    1150205    1219                      福壽實業股份有限公司        福壽
16    1150205    1220                      台榮產業股份有限公司        台榮
17    1150205    1225                      福懋油脂股份有限公司       福懋油
18    1150205    1227                      佳格食品股份有限公司        佳格
19    1150205    1229                    聯華實業控股股份有限公司        聯華
20    1150205    1231                    聯華食品工業股份有限公司       聯華食
21    1150205    1232                       大統益股份有限公司       大統益
22    1150205    1233                      天仁茶業股份有限公司        天仁
23    1150205    1234                        黑松股份有限公司        黑松
24    1150205    1235                      興泰實業股份有限公司        興泰
25    1150205    1236                      宏亞食品股份有限公司        宏亞
26    1150205    1256                      鮮活控股股份有限公司   鮮活果汁-KY
27    1150205    1301                    台灣塑膠工業股份有限公司        台塑
28    1150205    1303                    南亞塑膠工業股份有限公司        南亞
29    1150205    1304                   台灣聚合化學品股份有限公司        台聚
30    1150205    1305                    華夏海灣塑膠股份有限公司        華夏
31    1150205    1307                    三芳化學工業股份有限公司        三芳
32    1150205    1308                      亞洲聚合股份有限公司        亞聚
33    1150205    1309                    台達化學工業股份有限公司       台達化
34    1150205    1310                   台灣苯乙烯工業股份有限公司        台苯
35    1150205    1312                    國喬石油化學股份有限公司        國喬
36    1150205    1313                    聯成化學科技股份有限公司        聯成
37    1150205    1314                 中國石油化學工業開發(股)公司       中石化
38    1150205    1315                      達新工業股份有限公司        達新
39    1150205    1316                    上曜建設開發股份有限公司        上曜
40    1150205    1319                     東陽實業廠股份有限公司        東陽
41    1150205    1321                    大洋塑膠工業股份有限公司        大洋
42    1150205    1323                    永裕塑膠工業股份有限公司        永裕
43    1150205    1324                    地球綜合工業股份有限公司        地球
44    1150205    1325                        恒大股份有限公司        恆大
45    1150205    1326                    台灣化學纖維股份有限公司        台化
46    1150205    1337                  亞洲塑膠再生資源控股有限公司     再生-KY
47    1150205    1338                        廣華控股有限公司     廣華-KY
48    1150205    1339                      昭輝實業股份有限公司        昭輝
49    1150205    1340                       勝悅新材料有限公司     勝悅-KY
50    1150205    1341               富林塑膠工業(開曼)控股(股)公司     富林-KY
51    1150205    1342                      八貫企業股份有限公司        八貫
52    1150205    1402                     遠東新世紀股份有限公司       遠東新
53    1150205    1409                    新光合成纖維股份有限公司        新纖
54    1150205    1410                      南洋染整股份有限公司        南染
55    1150205    1413                    宏洲纖維工業股份有限公司        宏洲
56    1150205    1414                      東和紡織股份有限公司        東和
57    1150205    1416                      廣豐實業股份有限公司        廣豐
58    1150205    1417                        嘉裕股份有限公司        嘉裕
59    1150205    1418                       東華龍股份有限公司        東華
60    1150205    1419                      新光紡織股份有限公司        新紡
61    1150205    1423                    利華羊毛工業股份有限公司        利華
62    1150205    1432                     大魯閣實業股份有限公司       大魯閣
63    1150205    1434                      福懋興業股份有限公司        福懋
64    1150205    1435                       中福國際(股)公司        中福
65    1150205    1436                     華友聯開發股份有限公司       華友聯
66    1150205    1437                    勤益投資控股股份有限公司       勤益控
67    1150205    1438                    三地開發地產股份有限公司      三地開發
68    1150205    1439                      雋揚國際股份有限公司        雋揚
69    1150205    1440                      臺南紡織股份有限公司        南紡
70    1150205    1441                      大東紡織股份有限公司        大東
71    1150205    1442                      名軒開發股份有限公司        名軒
72    1150205    1443                    立益物流開發股份有限公司      立益物流
73    1150205    1444                      力麗企業股份有限公司        力麗
74    1150205    1445                      大宇紡織股份有限公司        大宇
75    1150205    1446                    宏和精密紡織股份有限公司        宏和
76    1150205    1447                      力鵬企業股份有限公司        力鵬
77    1150205    1449                      佳和實業股份有限公司        佳和
78    1150205    1451                      年興紡織股份有限公司        年興
79    1150205    1452                    宏益纖維工業股份有限公司        宏益
80    1150205    1453                      大將開發股份有限公司        大將
81    1150205    1454                    台灣富綢纖維股份有限公司        台富
82    1150205    1455                      集盛實業股份有限公司        集盛
83    1150205    1456                      怡華實業股份有限公司        怡華
84    1150205    1457                      宜進實業股份有限公司        宜進
85    1150205    1459                    聯發紡織纖維股份有限公司        聯發
86    1150205    1460                      宏遠興業股份有限公司        宏遠
87    1150205    1463                       強盛新股份有限公司       強盛新
88    1150205    1464                      得力實業股份有限公司        得力
89    1150205    1465                      偉全實業股份有限公司        偉全
90    1150205    1466                      聚隆纖維股份有限公司        聚隆
91    1150205    1467                      南緯實業股份有限公司        南緯
92    1150205    1468                    昶和纖維興業股份有限公司        昶和
93    1150205    1470                      大統新創股份有限公司      大統新創
94    1150205    1471                      首利實業股份有限公司        首利
95    1150205    1472                      三洋實業股份有限公司      三洋實業
96    1150205    1473                      台南企業股份有限公司        台南
97    1150205    1474                      弘裕企業股份有限公司        弘裕
98    1150205    1475                      台灣業旺股份有限公司        業旺
99    1150205    1476                      儒鴻企業股份有限公司        儒鴻
100   1150205    1477                      聚陽實業股份有限公司        聚陽
101   1150205    1503                     士林電機廠股份有限公司        士電
102   1150205    1504                      東元電機股份有限公司        東元
103   1150205    1506                      正道工業股份有限公司        正道
104   1150205    1512                      瑞利企業股份有限公司        瑞利
105   1150205    1513                    中興電工機械股份有限公司       中興電
106   1150205    1514                      亞力電機股份有限公司        亞力
107   1150205    1515                      力山工業股份有限公司        力山
108   1150205    1516                      川飛能源股份有限公司        川飛
109   1150205    1517                    利奇機械工業股份有限公司        利奇
110   1150205    1519                      華城電機股份有限公司        華城
111   1150205    1521                  大億交通工業製造股份有限公司        大億
112   1150205    1522                   堤維西交通工業股份有限公司       堤維西
113   1150205    1524                      耿鼎企業股份有限公司        耿鼎
114   1150205    1525                      江申工業股份有限公司        江申
115   1150205    1526                      日馳企業股份有限公司        日馳
116   1150205    1527                      鑽全實業股份有限公司        鑽全
117   1150205    1528                      恩德科技股份有限公司        恩德
118   1150205    1529                    樂事綠能科技股份有限公司      樂事綠能
119   1150205    1530                      亞崴機電股份有限公司        亞崴
120   1150205    1531                        高林股份有限公司       高林股
121   1150205    1532                        勤美股份有限公司        勤美
122   1150205    1533                      車王電子股份有限公司       車王電
123   1150205    1535                    中宇環保工程股份有限公司        中宇
124   1150205    1536                      和大工業股份有限公司        和大
125   1150205    1537                    廣隆光電科技股份有限公司        廣隆
126   1150205    1538                      正峰工業股份有限公司        正峰
127   1150205    1539                      巨庭機械股份有限公司        巨庭
128   1150205    1540                    喬福機械工業股份有限公司        喬福
129   1150205    1541                      錩泰工業股份有限公司        錩泰
130   1150205    1558                      伸興工業股份有限公司        伸興
131   1150205    1560                    中國砂輪企業股份有限公司        中砂
132   1150205    1563                    巧新科技工業股份有限公司        巧新
133   1150205    1568                      倉佑實業股份有限公司        倉佑
134   1150205    1582                      信錦企業股份有限公司        信錦
135   1150205    1583                      程泰機械股份有限公司        程泰
136   1150205    1587                      吉茂精密股份有限公司        吉茂
137   1150205    1589                    永冠能源科技集團有限公司     永冠-KY
138   1150205    1590                         亞德客國際集團    亞德客-KY
139   1150205    1597                      直得科技股份有限公司        直得
140   1150205    1598                      岱宇國際股份有限公司        岱宇
141   1150205    1603                    中華電線電纜股份有限公司        華電
142   1150205    1604                        聲寶股份有限公司        聲寶
143   1150205    1605                      華新麗華股份有限公司        華新
144   1150205    1608                    華榮電線電纜股份有限公司        華榮
145   1150205    1609                    大亞電線電纜股份有限公司        大亞
146   1150205    1611                      中國電器股份有限公司        中電
147   1150205    1612                      宏泰電工股份有限公司        宏泰
148   1150205    1614                    台灣三洋電機股份有限公司       三洋電
149   1150205    1615                    大山電線電纜股份有限公司        大山
150   1150205    1616                    億泰電線電纜股份有限公司        億泰
151   1150205    1617                    榮星電線工業股份有限公司        榮星
152   1150205    1618                    合機電線電纜股份有限公司        合機
153   1150205    1623                     大東電業廠股份有限公司       大東電
154   1150205    1626                   艾美特(開曼)國際有限公司    艾美特-KY
155   1150205    1702                    南僑投資控股股份有限公司        南僑
156   1150205    1707                     葡萄王生技股份有限公司       葡萄王
157   1150205    1708                      東南實業股份有限公司        東鹼
158   1150205    1709                    和益化學工業股份有限公司        和益
159   1150205    1710                      東聯化學股份有限公司        東聯
160   1150205    1711                  臺灣永光化學工業股份有限公司        永光
161   1150205    1712                        興農股份有限公司        興農
162   1150205    1713                     國泰化工廠股份有限公司        國化
163   1150205    1714                      和桐化學股份有限公司        和桐
164   1150205    1717                    長興材料工業股份有限公司        長興
165   1150205    1718                    中國人造纖維股份有限公司        中纖
166   1150205    1720                    生達化學製藥股份有限公司        生達
167   1150205    1721                        三晃股份有限公司        三晃
168   1150205    1722                      台灣肥料股份有限公司        台肥
169   1150205    1723                    中鋼碳素化學股份有限公司        中碳
170   1150205    1725                      元禎企業股份有限公司        元禎
171   1150205    1726                    永記造漆工業股份有限公司        永記
172   1150205    1727                  臺灣中華化學工業股份有限公司       中華化
173   1150205    1730                     花仙子企業股份有限公司       花仙子
174   1150205    1731                       美吾華股份有限公司       美吾華
175   1150205    1732                        毛寶股份有限公司        毛寶
176   1150205    1733                    五鼎生物技術股份有限公司        五鼎
177   1150205    1734                    杏輝藥品工業股份有限公司        杏輝
178   1150205    1735                      日勝化工股份有限公司       日勝化
179   1150205    1736                    喬山健康科技股份有限公司        喬山
180   1150205    1737                      臺鹽實業股份有限公司        臺鹽
181   1150205    1752                    南光化學製藥股份有限公司        南光
182   1150205    1760                    寶齡富錦生技股份有限公司      寶齡富錦
183   1150205    1762                    中化合成生技股份有限公司       中化生
184   1150205    1773                      勝一化工股份有限公司        勝一
185   1150205    1776                    展宇科技材料股份有限公司        展宇
186   1150205    1783                    和康生物科技股份有限公司       和康生
187   1150205    1786                    科妍生物科技股份有限公司        科妍
188   1150205    1789                      台灣神隆股份有限公司        神隆
189   1150205    1795                    美時化學製藥股份有限公司        美時
190   1150205    1802                    台灣玻璃工業股份有限公司        台玻
191   1150205    1805                      寶徠建設股份有限公司        寶徠
192   1150205    1806                      冠軍建材股份有限公司        冠軍
193   1150205    1808                      潤隆建設股份有限公司        潤隆
194   1150205    1809                      中國製釉股份有限公司        中釉
195   1150205    1810                      和成欣業股份有限公司        和成
196   1150205    1817                      凱撒衛浴股份有限公司       凱撒衛
197   1150205    1903                      士林紙業股份有限公司        士紙
198   1150205    1904                        正隆股份有限公司        正隆
199   1150205    1905                      中華紙漿股份有限公司        華紙
200   1150205    1906                      寶隆國際股份有限公司        寶隆
201   1150205    1907                   永豐餘投資控股股份有限公司       永豐餘
202   1150205    1909                      榮成紙業股份有限公司        榮成
203   1150205    2002                      中國鋼鐵股份有限公司        中鋼
204   1150205    2006                    東和鋼鐵企業股份有限公司      東和鋼鐵
205   1150205    2007                      燁興企業股份有限公司        燁興
206   1150205    2008                     高興昌鋼鐵股份有限公司       高興昌
207   1150205    2009                    第一伸銅科技股份有限公司       第一銅
208   1150205    2010                    春源鋼鐵工業股份有限公司        春源
209   1150205    2012                      春雨工廠股份有限公司        春雨
210   1150205    2013                    中國鋼鐵結構股份有限公司       中鋼構
211   1150205    2014                      中鴻鋼鐵股份有限公司        中鴻
212   1150205    2015                      豐興鋼鐵股份有限公司        豐興
213   1150205    2017                      官田鋼鐵股份有限公司       官田鋼
214   1150205    2020                     美亞鋼管廠股份有限公司        美亞
215   1150205    2022                      聚亨企業股份有限公司        聚亨
216   1150205    2023                      燁輝企業股份有限公司        燁輝
217   1150205    2024                      志聯工業股份有限公司        志聯
218   1150205    2025                      千興不銹鋼(股)公司        千興
219   1150205    2027                   大成不銹鋼工業股份有限公司       大成鋼
220   1150205    2028                    威致鋼鐵工業股份有限公司        威致
221   1150205    2029                        盛餘股份有限公司        盛餘
222   1150205    2030                      彰源企業股份有限公司        彰源
223   1150205    2031                      新光鋼鐵股份有限公司       新光鋼
224   1150205    2032                      新鋼工業股份有限公司        新鋼
225   1150205    2033                      佳大世界股份有限公司        佳大
226   1150205    2034                      允強實業股份有限公司        允強
227   1150205    2038                      海光企業股份有限公司        海光
228   1150205    2049                      上銀科技股份有限公司        上銀
229   1150205    2059                      川湖科技股份有限公司        川湖
230   1150205    2062                      橋椿金屬股份有限公司        橋椿
231   1150205    2069                      運錩鋼鐵股份有限公司        運錩
232   1150205    2101                      南港輪胎股份有限公司        南港
233   1150205    2102                      泰豐輪胎股份有限公司        泰豐
234   1150205    2103                        台橡股份有限公司        台橡
235   1150205    2104                  國際中橡投資控股股份有限公司      國際中橡
236   1150205    2105                    正新橡膠工業股份有限公司        正新
237   1150205    2106                      建大工業股份有限公司        建大
238   1150205    2107                        厚生股份有限公司        厚生
239   1150205    2108                    南帝化學工業股份有限公司        南帝
240   1150205    2109                    華豐橡膠工業股份有限公司        華豐
241   1150205    2114                       鑫永銓股份有限公司       鑫永銓
242   1150205    2115                      六暉控股股份有限公司     六暉-KY
243   1150205    2201                    裕隆汽車製造股份有限公司        裕隆
244   1150205    2204                    中華汽車工業股份有限公司        中華
245   1150205    2206                      三陽工業股份有限公司      三陽工業
246   1150205    2207                      和泰汽車股份有限公司       和泰車
247   1150205    2208                    台灣國際造船股份有限公司        台船
248   1150205    2211                      長榮鋼鐵股份有限公司       長榮鋼
249   1150205    2227                    裕隆日產汽車股份有限公司       裕日車
250   1150205    2228                        劍麟股份有限公司        劍麟
251   1150205    2231                    為升電裝工業股份有限公司        為升
252   1150205    2233                      宇隆科技股份有限公司        宇隆
253   1150205    2236                    百達精密工業股份有限公司     百達-KY
254   1150205    2239                    開曼英利工業股份有限公司     英利-KY
255   1150205    2241                     艾姆勒科技股份有限公司       艾姆勒
256   1150205    2243                      宏旭控股股份有限公司     宏旭-KY
257   1150205    2247                    汎德永業汽車股份有限公司      汎德永業
258   1150205    2248                    華勝汽車電子股份有限公司     華勝-KY
259   1150205    2250                第一化成控股(開曼)股份有限公司   IKKA-KY
260   1150205    2254                    巨鎧精密工業股份有限公司    巨鎧精密-創
261   1150205    2258                    鴻華先進科技股份有限公司    鴻華先進-創
262   1150205    2301                      光寶科技股份有限公司       光寶科
263   1150205    2302                    麗正國際科技股份有限公司        麗正
264   1150205    2303                      聯華電子股份有限公司        聯電
265   1150205    2305                      全友電腦股份有限公司        全友
266   1150205    2308                    台達電子工業股份有限公司       台達電
267   1150205    2312                    金寶電子工業股份有限公司        金寶
268   1150205    2313                      華通電腦股份有限公司        華通
269   1150205    2314                      台揚科技股份有限公司        台揚
270   1150205    2316                      楠梓電子股份有限公司       楠梓電
271   1150205    2317                    鴻海精密工業股份有限公司        鴻海
272   1150205    2321                        東訊股份有限公司        東訊
273   1150205    2323                        中環股份有限公司        中環
274   1150205    2324                    仁寶電腦工業股份有限公司        仁寶
275   1150205    2327                        國巨股份有限公司       國巨*
276   1150205    2328                      廣宇科技股份有限公司        廣宇
277   1150205    2329                      華泰電子股份有限公司        華泰
278   1150205    2330                  台灣積體電路製造股份有限公司       台積電
279   1150205    2331                      精英電腦股份有限公司        精英
280   1150205    2332                      友訊科技股份有限公司        友訊
281   1150205    2337                      旺宏電子股份有限公司        旺宏
282   1150205    2338                      台灣光罩股份有限公司        光罩
283   1150205    2340                     台亞半導體股份有限公司        台亞
284   1150205    2342                    台灣茂矽電子股份有限公司        茂矽
285   1150205    2344                      華邦電子股份有限公司       華邦電
286   1150205    2345                      智邦科技股份有限公司        智邦
287   1150205    2347                      聯強國際股份有限公司        聯強
288   1150205    2348                    海悅國際開發股份有限公司        海悅
289   1150205    2349                      錸德科技股份有限公司        錸德
290   1150205    2351                      順德工業股份有限公司        順德
291   1150205    2352                     佳世達科技股份有限公司       佳世達
292   1150205    2353                        宏碁股份有限公司        宏碁
293   1150205    2354                    鴻準精密工業股份有限公司        鴻準
294   1150205    2355                      敬鵬工業股份有限公司        敬鵬
295   1150205    2356                       英業達股份有限公司       英業達
296   1150205    2357                      華碩電腦股份有限公司        華碩
297   1150205    2359                       所羅門股份有限公司       所羅門
298   1150205    2360                      致茂電子股份有限公司        致茂
299   1150205    2362                      藍天電腦股份有限公司        藍天
300   1150205    2363                      矽統科技股份有限公司        矽統
301   1150205    2364                    倫飛電腦實業股份有限公司        倫飛
302   1150205    2365                      昆盈企業股份有限公司        昆盈
303   1150205    2367                      燿華電子股份有限公司        燿華
304   1150205    2368                       金像電子(股)公司       金像電
305   1150205    2369                    菱生精密工業股份有限公司        菱生
306   1150205    2371                        大同股份有限公司        大同
307   1150205    2373                       震旦行股份有限公司       震旦行
308   1150205    2374                      佳能企業股份有限公司        佳能
309   1150205    2375                      凱美電機股份有限公司        凱美
310   1150205    2376                      技嘉科技股份有限公司        技嘉

0       ﻿出表日期    公司代號                            公司名稱      公司簡稱  \
0     1150205    1101                      臺灣水泥股份有限公司        台泥
1     1150205    1102                      亞洲水泥股份有限公司        亞泥
2     1150205    1103                      嘉新水泥股份有限公司        嘉泥
3     1150205    1104                      環球水泥股份有限公司        環泥
4     1150205    1108                      幸福水泥股份有限公司        幸福
5     1150205    1109                      信大水泥股份有限公司        信大
6     1150205    1110                      東南水泥股份有限公司        東泥
7     1150205    1201                    味全食品工業股份有限公司        味全
8     1150205    1203                        味王股份有限公司        味王
9     1150205    1210                    大成長城企業股份有限公司        大成
10    1150205    1213                     大西洋飲料股份有限公司        大飲
11    1150205    1215                    台灣卜蜂企業股份有限公司        卜蜂
12    1150205    1216                      統一企業股份有限公司        統一
13    1150205    1217                       愛之味股份有限公司       愛之味
14    1150205    1218                      泰山企業股份有限公司        泰山
15    1150205    1219                      福壽實業股份有限公司        福壽
16    1150205    1220                      台榮產業股份有限公司        台榮
17    1150205    1225                      福懋油脂股份有限公司       福懋油
18    1150205    1227                      佳格食品股份有限公司        佳格
19    1150205    1229                    聯華實業控股股份有限公司        聯華
20    1150205    1231                    聯華食品工業股份有限公司       聯華食
21    1150205    1232                       大統益股份有限公司       大統益
22    1150205    1233                      天仁茶業股份有限公司        天仁
23    1150205    1234                        黑松股份有限公司        黑松
24    1150205    1235                      興泰實業股份有限公司        興泰
25    1150205    1236                      宏亞食品股份有限公司        宏亞
26    1150205    1256                      鮮活控股股份有限公司   鮮活果汁-KY
27    1150205    1301                    台灣塑膠工業股份有限公司        台塑
28    1150205    1303                    南亞塑膠工業股份有限公司        南亞
29    1150205    1304                   台灣聚合化學品股份有限公司        台聚
30    1150205    1305                    華夏海灣塑膠股份有限公司        華夏
31    1150205    1307                    三芳化學工業股份有限公司        三芳
32    1150205    1308                      亞洲聚合股份有限公司        亞聚
33    1150205    1309                    台達化學工業股份有限公司       台達化
34    1150205    1310                   台灣苯乙烯工業股份有限公司        台苯
35    1150205    1312                    國喬石油化學股份有限公司        國喬
36    1150205    1313                    聯成化學科技股份有限公司        聯成
37    1150205    1314                 中國石油化學工業開發(股)公司       中石化
38    1150205    1315                      達新工業股份有限公司        達新
39    1150205    1316                    上曜建設開發股份有限公司        上曜
40    1150205    1319                     東陽實業廠股份有限公司        東陽
41    1150205    1321                    大洋塑膠工業股份有限公司        大洋
42    1150205    1323                    永裕塑膠工業股份有限公司        永裕
43    1150205    1324                    地球綜合工業股份有限公司        地球
44    1150205    1325                        恒大股份有限公司        恆大
45    1150205    1326                    台灣化學纖維股份有限公司        台化
46    1150205    1337                  亞洲塑膠再生資源控股有限公司     再生-KY
47    1150205    1338                        廣華控股有限公司     廣華-KY
48    1150205    1339                      昭輝實業股份有限公司        昭輝
49    1150205    1340                       勝悅新材料有限公司     勝悅-KY
50    1150205    1341               富林塑膠工業(開曼)控股(股)公司     富林-KY
51    1150205    1342                      八貫企業股份有限公司        八貫
52    1150205    1402                     遠東新世紀股份有限公司       遠東新
53    1150205    1409                    新光合成纖維股份有限公司        新纖
54    1150205    1410                      南洋染整股份有限公司        南染
55    1150205    1413                    宏洲纖維工業股份有限公司        宏洲
56    1150205    1414                      東和紡織股份有限公司        東和
57    1150205    1416                      廣豐實業股份有限公司        廣豐
58    1150205    1417                        嘉裕股份有限公司        嘉裕
59    1150205    1418                       東華龍股份有限公司        東華
60    1150205    1419                      新光紡織股份有限公司        新紡
61    1150205    1423                    利華羊毛工業股份有限公司        利華
62    1150205    1432                     大魯閣實業股份有限公司       大魯閣
63    1150205    1434                      福懋興業股份有限公司        福懋
64    1150205    1435                       中福國際(股)公司        中福
65    1150205    1436                     華友聯開發股份有限公司       華友聯
66    1150205    1437                    勤益投資控股股份有限公司       勤益控
67    1150205    1438                    三地開發地產股份有限公司      三地開發
68    1150205    1439                      雋揚國際股份有限公司        雋揚
69    1150205    1440                      臺南紡織股份有限公司        南紡
70    1150205    1441                      大東紡織股份有限公司        大東
71    1150205    1442                      名軒開發股份有限公司        名軒
72    1150205    1443                    立益物流開發股份有限公司      立益物流
73    1150205    1444                      力麗企業股份有限公司        力麗
74    1150205    1445                      大宇紡織股份有限公司        大宇
75    1150205    1446                    宏和精密紡織股份有限公司        宏和
76    1150205    1447                      力鵬企業股份有限公司        力鵬
77    1150205    1449                      佳和實業股份有限公司        佳和
78    1150205    1451                      年興紡織股份有限公司        年興
79    1150205    1452                    宏益纖維工業股份有限公司        宏益
80    1150205    1453                      大將開發股份有限公司        大將
81    1150205    1454                    台灣富綢纖維股份有限公司        台富
82    1150205    1455                      集盛實業股份有限公司        集盛
83    1150205    1456                      怡華實業股份有限公司        怡華
84    1150205    1457                      宜進實業股份有限公司        宜進
85    1150205    1459                    聯發紡織纖維股份有限公司        聯發
86    1150205    1460                      宏遠興業股份有限公司        宏遠
87    1150205    1463                       強盛新股份有限公司       強盛新
88    1150205    1464                      得力實業股份有限公司        得力
89    1150205    1465                      偉全實業股份有限公司        偉全
90    1150205    1466                      聚隆纖維股份有限公司        聚隆
91    1150205    1467                      南緯實業股份有限公司        南緯
92    1150205    1468                    昶和纖維興業股份有限公司        昶和
93    1150205    1470                      大統新創股份有限公司      大統新創
94    1150205    1471                      首利實業股份有限公司        首利
95    1150205    1472                      三洋實業股份有限公司      三洋實業
96    1150205    1473                      台南企業股份有限公司        台南
97    1150205    1474                      弘裕企業股份有限公司        弘裕
98    1150205    1475                      台灣業旺股份有限公司        業旺
99    1150205    1476                      儒鴻企業股份有限公司        儒鴻
100   1150205    1477                      聚陽實業股份有限公司        聚陽
101   1150205    1503                     士林電機廠股份有限公司        士電
102   1150205    1504                      東元電機股份有限公司        東元
103   1150205    1506                      正道工業股份有限公司        正道
104   1150205    1512                      瑞利企業股份有限公司        瑞利
105   1150205    1513                    中興電工機械股份有限公司       中興電
106   1150205    1514                      亞力電機股份有限公司        亞力
107   1150205    1515                      力山工業股份有限公司        力山
108   1150205    1516                      川飛能源股份有限公司        川飛
109   1150205    1517                    利奇機械工業股份有限公司        利奇
110   1150205    1519                      華城電機股份有限公司        華城
111   1150205    1521                  大億交通工業製造股份有限公司        大億
112   1150205    1522                   堤維西交通工業股份有限公司       堤維西
113   1150205    1524                      耿鼎企業股份有限公司        耿鼎
114   1150205    1525                      江申工業股份有限公司        江申
115   1150205    1526                      日馳企業股份有限公司        日馳
116   1150205    1527                      鑽全實業股份有限公司        鑽全
117   1150205    1528                      恩德科技股份有限公司        恩德
118   1150205    1529                    樂事綠能科技股份有限公司      樂事綠能
119   1150205    1530                      亞崴機電股份有限公司        亞崴
120   1150205    1531                        高林股份有限公司       高林股
121   1150205    1532                        勤美股份有限公司        勤美
122   1150205    1533                      車王電子股份有限公司       車王電
123   1150205    1535                    中宇環保工程股份有限公司        中宇
124   1150205    1536                      和大工業股份有限公司        和大
125   1150205    1537                    廣隆光電科技股份有限公司        廣隆
126   1150205    1538                      正峰工業股份有限公司        正峰
127   1150205    1539                      巨庭機械股份有限公司        巨庭
128   1150205    1540                    喬福機械工業股份有限公司        喬福
129   1150205    1541                      錩泰工業股份有限公司        錩泰
130   1150205    1558                      伸興工業股份有限公司        伸興
131   1150205    1560                    中國砂輪企業股份有限公司        中砂
132   1150205    1563                    巧新科技工業股份有限公司        巧新
133   1150205    1568                      倉佑實業股份有限公司        倉佑
134   1150205    1582                      信錦企業股份有限公司        信錦
135   1150205    1583                      程泰機械股份有限公司        程泰
136   1150205    1587                      吉茂精密股份有限公司        吉茂
137   1150205    1589                    永冠能源科技集團有限公司     永冠-KY
138   1150205    1590                         亞德客國際集團    亞德客-KY
139   1150205    1597                      直得科技股份有限公司        直得
140   1150205    1598                      岱宇國際股份有限公司        岱宇
141   1150205    1603                    中華電線電纜股份有限公司        華電
142   1150205    1604                        聲寶股份有限公司        聲寶
143   1150205    1605                      華新麗華股份有限公司        華新
144   1150205    1608                    華榮電線電纜股份有限公司        華榮
145   1150205    1609                    大亞電線電纜股份有限公司        大亞
146   1150205    1611                      中國電器股份有限公司        中電
147   1150205    1612                      宏泰電工股份有限公司        宏泰
148   1150205    1614                    台灣三洋電機股份有限公司       三洋電
149   1150205    1615                    大山電線電纜股份有限公司        大山
150   1150205    1616                    億泰電線電纜股份有限公司        億泰
151   1150205    1617                    榮星電線工業股份有限公司        榮星
152   1150205    1618                    合機電線電纜股份有限公司        合機
153   1150205    1623                     大東電業廠股份有限公司       大東電
154   1150205    1626                   艾美特(開曼)國際有限公司    艾美特-KY
155   1150205    1702                    南僑投資控股股份有限公司        南僑
156   1150205    1707                     葡萄王生技股份有限公司       葡萄王
157   1150205    1708                      東南實業股份有限公司        東鹼
158   1150205    1709                    和益化學工業股份有限公司        和益
159   1150205    1710                      東聯化學股份有限公司        東聯
160   1150205    1711                  臺灣永光化學工業股份有限公司        永光
161   1150205    1712                        興農股份有限公司        興農
162   1150205    1713                     國泰化工廠股份有限公司        國化
163   1150205    1714                      和桐化學股份有限公司        和桐
164   1150205    1717                    長興材料工業股份有限公司        長興
165   1150205    1718                    中國人造纖維股份有限公司        中纖
166   1150205    1720                    生達化學製藥股份有限公司        生達
167   1150205    1721                        三晃股份有限公司        三晃
168   1150205    1722                      台灣肥料股份有限公司        台肥
169   1150205    1723                    中鋼碳素化學股份有限公司        中碳
170   1150205    1725                      元禎企業股份有限公司        元禎
171   1150205    1726                    永記造漆工業股份有限公司        永記
172   1150205    1727                  臺灣中華化學工業股份有限公司       中華化
173   1150205    1730                     花仙子企業股份有限公司       花仙子
174   1150205    1731                       美吾華股份有限公司       美吾華
175   1150205    1732                        毛寶股份有限公司        毛寶
176   1150205    1733                    五鼎生物技術股份有限公司        五鼎
177   1150205    1734                    杏輝藥品工業股份有限公司        杏輝
178   1150205    1735                      日勝化工股份有限公司       日勝化
179   1150205    1736                    喬山健康科技股份有限公司        喬山
180   1150205    1737                      臺鹽實業股份有限公司        臺鹽
181   1150205    1752                    南光化學製藥股份有限公司        南光
182   1150205    1760                    寶齡富錦生技股份有限公司      寶齡富錦
183   1150205    1762                    中化合成生技股份有限公司       中化生
184   1150205    1773                      勝一化工股份有限公司        勝一
185   1150205    1776                    展宇科技材料股份有限公司        展宇
186   1150205    1783                    和康生物科技股份有限公司       和康生
187   1150205    1786                    科妍生物科技股份有限公司        科妍
188   1150205    1789                      台灣神隆股份有限公司        神隆
189   1150205    1795                    美時化學製藥股份有限公司        美時
190   1150205    1802                    台灣玻璃工業股份有限公司        台玻
191   1150205    1805                      寶徠建設股份有限公司        寶徠
192   1150205    1806                      冠軍建材股份有限公司        冠軍
193   1150205    1808                      潤隆建設股份有限公司        潤隆
194   1150205    1809                      中國製釉股份有限公司        中釉
195   1150205    1810                      和成欣業股份有限公司        和成
196   1150205    1817                      凱撒衛浴股份有限公司       凱撒衛
197   1150205    1903                      士林紙業股份有限公司        士紙
198   1150205    1904                        正隆股份有限公司        正隆
199   1150205    1905                      中華紙漿股份有限公司        華紙
200   1150205    1906                      寶隆國際股份有限公司        寶隆
201   1150205    1907                   永豐餘投資控股股份有限公司       永豐餘
202   1150205    1909                      榮成紙業股份有限公司        榮成
203   1150205    2002                      中國鋼鐵股份有限公司        中鋼
204   1150205    2006                    東和鋼鐵企業股份有限公司      東和鋼鐵
205   1150205    2007                      燁興企業股份有限公司        燁興
206   1150205    2008                     高興昌鋼鐵股份有限公司       高興昌
207   1150205    2009                    第一伸銅科技股份有限公司       第一銅
208   1150205    2010                    春源鋼鐵工業股份有限公司        春源
209   1150205    2012                      春雨工廠股份有限公司        春雨
210   1150205    2013                    中國鋼鐵結構股份有限公司       中鋼構
211   1150205    2014                      中鴻鋼鐵股份有限公司        中鴻
212   1150205    2015                      豐興鋼鐵股份有限公司        豐興
213   1150205    2017                      官田鋼鐵股份有限公司       官田鋼
214   1150205    2020                     美亞鋼管廠股份有限公司        美亞
215   1150205    2022                      聚亨企業股份有限公司        聚亨
216   1150205    2023                      燁輝企業股份有限公司        燁輝
217   1150205    2024                      志聯工業股份有限公司        志聯
218   1150205    2025                      千興不銹鋼(股)公司        千興
219   1150205    2027                   大成不銹鋼工業股份有限公司       大成鋼
220   1150205    2028                    威致鋼鐵工業股份有限公司        威致
221   1150205    2029                        盛餘股份有限公司        盛餘
222   1150205    2030                      彰源企業股份有限公司        彰源
223   1150205    2031                      新光鋼鐵股份有限公司       新光鋼
224   1150205    2032                      新鋼工業股份有限公司        新鋼
225   1150205    2033                      佳大世界股份有限公司        佳大
226   1150205    2034                      允強實業股份有限公司        允強
227   1150205    2038                      海光企業股份有限公司        海光
228   1150205    2049                      上銀科技股份有限公司        上銀
229   1150205    2059                      川湖科技股份有限公司        川湖
230   1150205    2062                      橋椿金屬股份有限公司        橋椿
231   1150205    2069                      運錩鋼鐵股份有限公司        運錩
232   1150205    2101                      南港輪胎股份有限公司        南港
233   1150205    2102                      泰豐輪胎股份有限公司        泰豐
234   1150205    2103                        台橡股份有限公司        台橡
235   1150205    2104                  國際中橡投資控股股份有限公司      國際中橡
236   1150205    2105                    正新橡膠工業股份有限公司        正新
237   1150205    2106                      建大工業股份有限公司        建大
238   1150205    2107                        厚生股份有限公司        厚生
239   1150205    2108                    南帝化學工業股份有限公司        南帝
240   1150205    2109                    華豐橡膠工業股份有限公司        華豐
241   1150205    2114                       鑫永銓股份有限公司       鑫永銓
242   1150205    2115                      六暉控股股份有限公司     六暉-KY
243   1150205    2201                    裕隆汽車製造股份有限公司        裕隆
244   1150205    2204                    中華汽車工業股份有限公司        中華
245   1150205    2206                      三陽工業股份有限公司      三陽工業
246   1150205    2207                      和泰汽車股份有限公司       和泰車
247   1150205    2208                    台灣國際造船股份有限公司        台船
248   1150205    2211                      長榮鋼鐵股份有限公司       長榮鋼
249   1150205    2227                    裕隆日產汽車股份有限公司       裕日車
250   1150205    2228                        劍麟股份有限公司        劍麟
251   1150205    2231                    為升電裝工業股份有限公司        為升
252   1150205    2233                      宇隆科技股份有限公司        宇隆
253   1150205    2236                    百達精密工業股份有限公司     百達-KY
254   1150205    2239                    開曼英利工業股份有限公司     英利-KY
255   1150205    2241                     艾姆勒科技股份有限公司       艾姆勒
256   1150205    2243                      宏旭控股股份有限公司     宏旭-KY
257   1150205    2247                    汎德永業汽車股份有限公司      汎德永業
258   1150205    2248                    華勝汽車電子股份有限公司     華勝-KY
259   1150205    2250                第一化成控股(開曼)股份有限公司   IKKA-KY
260   1150205    2254                    巨鎧精密工業股份有限公司    巨鎧精密-創
261   1150205    2258                    鴻華先進科技股份有限公司    鴻華先進-創
262   1150205    2301                      光寶科技股份有限公司       光寶科
263   1150205    2302                    麗正國際科技股份有限公司        麗正
264   1150205    2303                      聯華電子股份有限公司        聯電
265   1150205    2305                      全友電腦股份有限公司        全友
266   1150205    2308                    台達電子工業股份有限公司       台達電
267   1150205    2312                    金寶電子工業股份有限公司        金寶
268   1150205    2313                      華通電腦股份有限公司        華通
269   1150205    2314                      台揚科技股份有限公司        台揚
270   1150205    2316                      楠梓電子股份有限公司       楠梓電
271   1150205    2317                    鴻海精密工業股份有限公司        鴻海
272   1150205    2321                        東訊股份有限公司        東訊
273   1150205    2323                        中環股份有限公司        中環
274   1150205    2324                    仁寶電腦工業股份有限公司        仁寶
275   1150205    2327                        國巨股份有限公司       國巨*
276   1150205    2328                      廣宇科技股份有限公司        廣宇
277   1150205    2329                      華泰電子股份有限公司        華泰
278   1150205    2330                  台灣積體電路製造股份有限公司       台積電
279   1150205    2331                      精英電腦股份有限公司        精英
280   1150205    2332                      友訊科技股份有限公司        友訊
281   1150205    2337                      旺宏電子股份有限公司        旺宏
282   1150205    2338                      台灣光罩股份有限公司        光罩
283   1150205    2340                     台亞半導體股份有限公司        台亞
284   1150205    2342                    台灣茂矽電子股份有限公司        茂矽
285   1150205    2344                      華邦電子股份有限公司       華邦電
286   1150205    2345                      智邦科技股份有限公司        智邦
287   1150205    2347                      聯強國際股份有限公司        聯強
288   1150205    2348                    海悅國際開發股份有限公司        海悅
289   1150205    2349                      錸德科技股份有限公司        錸德
290   1150205    2351                      順德工業股份有限公司        順德
291   1150205    2352                     佳世達科技股份有限公司       佳世達
292   1150205    2353                        宏碁股份有限公司        宏碁
293   1150205    2354                    鴻準精密工業股份有限公司        鴻準
294   1150205    2355                      敬鵬工業股份有限公司        敬鵬
295   1150205    2356                       英業達股份有限公司       英業達
296   1150205    2357                      華碩電腦股份有限公司        華碩
297   1150205    2359                       所羅門股份有限公司       所羅門
298   1150205    2360                      致茂電子股份有限公司        致茂
299   1150205    2362                      藍天電腦股份有限公司        藍天
300   1150205    2363                      矽統科技股份有限公司        矽統
301   1150205    2364                    倫飛電腦實業股份有限公司        倫飛
302   1150205    2365                      昆盈企業股份有限公司        昆盈
303   1150205    2367                      燿華電子股份有限公司        燿華
304   1150205    2368                       金像電子(股)公司       金像電
305   1150205    2369                    菱生精密工業股份有限公司        菱生
306   1150205    2371                        大同股份有限公司        大同
307   1150205    2373                       震旦行股份有限公司       震旦行
308   1150205    2374                      佳能企業股份有限公司        佳能
309   1150205    2375                      凱美電機股份有限公司        凱美
310   1150205    2376                      技嘉科技股份有限公司        技嘉

# 上櫃公司基本資料

In [7]:
# UI:https://data.gov.tw/dataset/25036
url='https://mopsfin.twse.com.tw/opendata/t187ap03_O.csv'
#若有 CSV 可以選用True 做更新 False 會直接讀2021/07/16 下載的資料
updatamappingData=False
headers = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"
}
req = requests.get(url, headers = headers,verify=False)
data = req.content.decode('utf8')
dfOCT = pd.DataFrame([x.replace('"','').split(',') for x in data.split('\n')])
dfOCT  = pd.DataFrame(dfOCT .values[1:], columns=dfOCT .iloc[0])
dfOCT['Type']='上櫃'
dfOCT1=dfOCT[['公司代號', '公司名稱', '公司簡稱','產業別','實收資本額','Type']]

#【解碼產業】
#【Data 合併】
dfOCT_=pd.merge(dfOCT1, mappingData, how='left', left_on='產業別', right_on='新編碼')

In [8]:
# output 上市上櫃股票資訊
pd.concat([df_listing2, dfOCT_]).to_csv(r'BaseInfo/StockBaseData.csv', index = False, encoding='utf-8', errors='ignore')
#給人看得
pd.concat([df_listing2, dfOCT_]).to_csv(r'Result/StockBaseDataRead.csv', index = False,encoding='big5', errors='ignore')
_baseInfo=pd.concat([df_listing2, dfOCT_])
_baseInfo=_baseInfo[~_baseInfo['公司代號'].isna()]

len(_baseInfo)